### ISSUE TITLE
enum values are duplicated when using oneOf

### ISSUE THREAD

**Issue by Skynet6** [rjsf-team/react-jsonschema-form#1162]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ x] Ideally, I'm providing [a shared playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6Ik9wdGlvbjEifV0sImZpcnN0TmFtZSI6IkNodWNrIiwibGFzdE5hbWUiOiJOb3JyaXMiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIn0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNi9zY2hlbWEjIiwiJGlkIjoiUHJvZHVjdElkIiwidGl0bGUiOiJQcm9kdWN0MSIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCAxIiwidHlwZSI6Im9iamVjdCIsImRlZmluaXRpb25zIjp7IlBhcnRpY2lwYXRpb24iOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiRGlyZWN0aW9uIjp7ImRlc2NyaXB0aW9uIjoiRGlyZWN0aW9uIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiRG93biJdLCJkZWZhdWx0IjoiRG93biJ9LCJPcHRpb25UeXBlIjp7ImVudW0iOlsiT3B0aW9uMSIsIkN1c3RvbU9wdGlvbjEiXSwiZGVmYXVsdCI6Ik9wdGlvbjEifX0sInJlcXVpcmVkIjpbIkRpcmVjdGlvbiJdLCJkZXBlbmRlbmNpZXMiOnsiRGlyZWN0aW9uIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IkRpcmVjdGlvbiI6eyJlbnVtIjpbIkRvd24iXX0sIk9wdGlvblR5cGUiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gdHlwZSIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIk9wdGlvbjEiLCJDdXN0b21PcHRpb24xIl19fSwicmVxdWlyZWQiOlsiT3B0aW9uVHlwZSJdLCJkZXBlbmRlbmNpZXMiOnsiT3B0aW9uVHlwZSI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJPcHRpb25UeXBlIjp7ImVudW0iOlsiT3B0aW9uMSJdfSwiQmx1ZSI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBCbHVlIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsInJlYWRPbmx5Ijp0cnVlLCJtaW5pbXVtIjoxLCJtYXhpbXVtIjoxfSwiUmVkIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIFJlZCIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJyZWFkT25seSI6dHJ1ZSwibWluaW11bSI6MSwibWF4aW11bSI6MX0sIlllbGxvdyI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBZZWxsb3ciLCJ0eXBlIjoibnVtYmVyIiwibWF4aW11bSI6MSwibWluaW11bSI6MH0sIkdyZWVuIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEdyZWVuIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIk9wdGlvbjIiLCJPcHRpb24zIl19fSwicmVxdWlyZWQiOlsiQmx1ZSIsIlJlZCIsIlllbGxvdyIsIkdyZWVuIl19LHsicHJvcGVydGllcyI6eyJPcHRpb25UeXBlIjp7ImVudW0iOlsiQ3VzdG9tT3B0aW9uMSJdfSwiQmx1ZSI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBCbHVlIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsIm1pbmltdW0iOjB9LCJSZWQiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gUmVkIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsIm1pbmltdW0iOjB9LCJCbGFjayI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBCbGFjayIsInR5cGUiOiJudW1iZXIiLCJtYXhpbXVtIjoxLCJtaW5pbXVtIjowfSwiR3JlZW4iOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gR3JlZW4iLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPcHRpb24xIiwiT3B0aW9uMiIsIk9wdGlvbjMiXX19LCJyZXF1aXJlZCI6WyJCbHVlIiwiUmVkIiwiQmxhY2siLCJHcmVlbiJdfV19fX1dfX19LCJ1bmlxdWVJdGVtcyI6dHJ1ZSwibWluSXRlbXMiOjEsIm1heEl0ZW1zIjoxfX0sInByb3BlcnRpZXMiOnsiUGFydGljaXBhdGlvbiI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9QYXJ0aWNpcGF0aW9uIn19LCJyZXF1aXJlZCI6WyJQYXJ0aWNpcGF0aW9uIl19LCJ1aVNjaGVtYSI6e319) demonstrating the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Create a schema with oneOf, containing an enum with at least two values
2. Create two branches that will specify fields for a specific enum value

#### Expected behavior

Generated enum will contain two values

#### Actual behavior

Generated enum contains four values.

### Version

1.2

Shared playground link provided above.

**Comment by LucianBuzzo** [comment]
I need to dig deeper into why this is happening, but I noticed that your schema seems to unnecessarily declare `OptionType` twice - removing the nested declaration prevents the duplicated enum values from appearing whilst maintaining the intention of the schema.
https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6IkN1c3RvbU9wdGlvbjEifV0sImZpcnN0TmFtZSI6IkNodWNrIiwibGFzdE5hbWUiOiJOb3JyaXMiLCJhZ2UiOjc1LCJiaW8iOiJSb3VuZGhvdXNlIGtpY2tpbmcgYXNzZXMgc2luY2UgMTk0MCIsInBhc3N3b3JkIjoibm9uZWVkIn0sInNjaGVtYSI6eyIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNi9zY2hlbWEjIiwiJGlkIjoiUHJvZHVjdElkIiwidGl0bGUiOiJQcm9kdWN0MSIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCAxIiwidHlwZSI6Im9iamVjdCIsImRlZmluaXRpb25zIjp7IlBhcnRpY2lwYXRpb24iOnsidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiRGlyZWN0aW9uIjp7ImRlc2NyaXB0aW9uIjoiRGlyZWN0aW9uIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiRG93biJdLCJkZWZhdWx0IjoiRG93biJ9LCJPcHRpb25UeXBlIjp7ImVudW0iOlsiT3B0aW9uMSIsIkN1c3RvbU9wdGlvbjEiXSwiZGVmYXVsdCI6Ik9wdGlvbjEifX0sInJlcXVpcmVkIjpbIkRpcmVjdGlvbiJdLCJkZXBlbmRlbmNpZXMiOnsiRGlyZWN0aW9uIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IkRpcmVjdGlvbiI6eyJlbnVtIjpbIkRvd24iXX19LCJyZXF1aXJlZCI6WyJPcHRpb25UeXBlIl0sImRlcGVuZGVuY2llcyI6eyJPcHRpb25UeXBlIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7Ik9wdGlvblR5cGUiOnsiZW51bSI6WyJPcHRpb24xIl19LCJCbHVlIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEJsdWUiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwicmVhZE9ubHkiOnRydWUsIm1pbmltdW0iOjEsIm1heGltdW0iOjF9LCJSZWQiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gUmVkIiwidHlwZSI6Im51bWJlciIsImRlZmF1bHQiOjEsInJlYWRPbmx5Ijp0cnVlLCJtaW5pbXVtIjoxLCJtYXhpbXVtIjoxfSwiWWVsbG93Ijp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIFllbGxvdyIsInR5cGUiOiJudW1iZXIiLCJtYXhpbXVtIjoxLCJtaW5pbXVtIjowfSwiR3JlZW4iOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gR3JlZW4iLCJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJPcHRpb24xIiwiT3B0aW9uMiIsIk9wdGlvbjMiXX19LCJyZXF1aXJlZCI6WyJCbHVlIiwiUmVkIiwiWWVsbG93IiwiR3JlZW4iXX0seyJwcm9wZXJ0aWVzIjp7Ik9wdGlvblR5cGUiOnsiZW51bSI6WyJDdXN0b21PcHRpb24xIl19LCJCbHVlIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEJsdWUiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwibWluaW11bSI6MH0sIlJlZCI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBSZWQiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwibWluaW11bSI6MH0sIkJsYWNrIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEJsYWNrIiwidHlwZSI6Im51bWJlciIsIm1heGltdW0iOjEsIm1pbmltdW0iOjB9LCJHcmVlbiI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBHcmVlbiIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIk9wdGlvbjEiLCJPcHRpb24yIiwiT3B0aW9uMyJdfX0sInJlcXVpcmVkIjpbIkJsdWUiLCJSZWQiLCJCbGFjayIsIkdyZWVuIl19XX19fV19fX0sInVuaXF1ZUl0ZW1zIjp0cnVlLCJtaW5JdGVtcyI6MSwibWF4SXRlbXMiOjF9fSwicHJvcGVydGllcyI6eyJQYXJ0aWNpcGF0aW9uIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1BhcnRpY2lwYXRpb24ifX0sInJlcXVpcmVkIjpbIlBhcnRpY2lwYXRpb24iXX0sInVpU2NoZW1hIjp7fX0=

**Comment by LucianBuzzo** [comment]
Here is a [minimal reproduction](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6ImZvbyJ9XX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJQYXJ0aWNpcGF0aW9uIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkRpcmVjdGlvbiI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IkRvd24ifSwiT3B0aW9uVHlwZSI6eyJlbnVtIjpbImZvbyJdLCJkZWZhdWx0IjoiZm9vIn19LCJkZXBlbmRlbmNpZXMiOnsiRGlyZWN0aW9uIjp7InByb3BlcnRpZXMiOnsiT3B0aW9uVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb28iXX19fX19fX19LCJ1aVNjaGVtYSI6e319l) of the issue.

**Comment by epicfaace** [comment]
> Here is a [minimal reproduction](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIiwiT3B0aW9uVHlwZSI6ImZvbyJ9XX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJQYXJ0aWNpcGF0aW9uIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkRpcmVjdGlvbiI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6IkRvd24ifSwiT3B0aW9uVHlwZSI6eyJlbnVtIjpbImZvbyJdLCJkZWZhdWx0IjoiZm9vIn19LCJkZXBlbmRlbmNpZXMiOnsiRGlyZWN0aW9uIjp7InByb3BlcnRpZXMiOnsiT3B0aW9uVHlwZSI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJmb28iXX19fX19fX19LCJ1aVNjaGVtYSI6e319l) of the issue.

@LucianBuzzo I get an error saying "Unable to load form setup data." when opening the above link.

**Comment by hasan-li** [comment]
@LucianBuzzo 


The problem here is that schema has 3 levels of dependecies. 

```
|─Direction (Down)
|─OptionType (Option1, CustomOption1)
|────OptionType (Option1, CustomOption1)
|───────Blue
|───────Red
|───────Yellow
|───────Green
```

As you see `OptionType` is the conditional dependency, so problem could be solved if `OptionType` is removed from top level. But in that case the default value of `OptionType` in nested dependency won't enable conditional dependencies in it's nested dependencies, so fields `Blue, Red, Yellow and Green` won't visible

Providing [example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJQYXJ0aWNpcGF0aW9uIjpbeyJEaXJlY3Rpb24iOiJEb3duIn1dLCJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDYvc2NoZW1hIyIsIiRpZCI6IlByb2R1Y3RJZCIsInRpdGxlIjoiUHJvZHVjdDEiLCJkZXNjcmlwdGlvbiI6IlByb2R1Y3QgMSIsInR5cGUiOiJvYmplY3QiLCJkZWZpbml0aW9ucyI6eyJQYXJ0aWNpcGF0aW9uIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkRhdGFJZCI6eyJkZXNjcmlwdGlvbiI6IkRhdGEgSUQiLCJ0eXBlIjoic3RyaW5nIiwiJHR5cGUiOiJyZWZlcmVuY2UiLCIkZGF0YSI6IiQuRGF0YS4uRGF0YUlkIn0sIkRpcmVjdGlvbiI6eyJkZXNjcmlwdGlvbiI6IkRpcmVjdGlvbiIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIkRvd24iXSwiZGVmYXVsdCI6IkRvd24ifX0sInJlcXVpcmVkIjpbIlBlcmZvcm1hbmNlIiwiRGlyZWN0aW9uIl0sImRlcGVuZGVuY2llcyI6eyJEaXJlY3Rpb24iOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiRGlyZWN0aW9uIjp7ImVudW0iOlsiRG93biJdfSwiT3B0aW9uVHlwZSI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiB0eXBlIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIkN1c3RvbU9wdGlvbjEiXSwiZGVmYXVsdCI6Ik9wdGlvbjEifX0sInJlcXVpcmVkIjpbIk9wdGlvblR5cGUiXSwiZGVwZW5kZW5jaWVzIjp7Ik9wdGlvblR5cGUiOnsib25lT2YiOlt7InByb3BlcnRpZXMiOnsiT3B0aW9uVHlwZSI6eyJlbnVtIjpbIk9wdGlvbjEiXX0sIkJsdWUiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gQmx1ZSIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJyZWFkT25seSI6dHJ1ZSwibWluaW11bSI6MSwibWF4aW11bSI6MX0sIlJlZCI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBSZWQiLCJ0eXBlIjoibnVtYmVyIiwiZGVmYXVsdCI6MSwicmVhZE9ubHkiOnRydWUsIm1pbmltdW0iOjEsIm1heGltdW0iOjF9LCJZZWxsb3ciOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gWWVsbG93IiwidHlwZSI6Im51bWJlciIsIm1heGltdW0iOjEsIm1pbmltdW0iOjB9LCJHcmVlbiI6eyJkZXNjcmlwdGlvbiI6Ik9wdGlvbiBHcmVlbiIsInR5cGUiOiJzdHJpbmciLCJlbnVtIjpbIk9wdGlvbjEiLCJPcHRpb24yIiwiT3B0aW9uMyJdfX0sInJlcXVpcmVkIjpbIkJsdWUiLCJSZWQiLCJZZWxsb3ciLCJHcmVlbiJdfSx7InByb3BlcnRpZXMiOnsiT3B0aW9uVHlwZSI6eyJlbnVtIjpbIkN1c3RvbU9wdGlvbjEiXX0sIkJsdWUiOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gQmx1ZSIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJtaW5pbXVtIjowfSwiUmVkIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIFJlZCIsInR5cGUiOiJudW1iZXIiLCJkZWZhdWx0IjoxLCJtaW5pbXVtIjowfSwiQmxhY2siOnsiZGVzY3JpcHRpb24iOiJPcHRpb24gQmxhY2siLCJ0eXBlIjoibnVtYmVyIiwibWF4aW11bSI6MSwibWluaW11bSI6MH0sIkdyZWVuIjp7ImRlc2NyaXB0aW9uIjoiT3B0aW9uIEdyZWVuIiwidHlwZSI6InN0cmluZyIsImVudW0iOlsiT3B0aW9uMSIsIk9wdGlvbjIiLCJPcHRpb24zIl19fSwicmVxdWlyZWQiOlsiQmx1ZSIsIlJlZCIsIkJsYWNrIiwiR3JlZW4iXX1dfX19XX19fSwidW5pcXVlSXRlbXMiOnRydWUsIm1pbkl0ZW1zIjoxLCJtYXhJdGVtcyI6MX19LCJwcm9wZXJ0aWVzIjp7IlBhcnRpY2lwYXRpb24iOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvUGFydGljaXBhdGlvbiJ9fSwicmVxdWlyZWQiOlsiUGFydGljaXBhdGlvbiJdfSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19fQ==)

**Comment by travisdahl** [comment]
@epicfaace any updates on this? its been open for quite some time. Also the playground is down, I was going to try and create a simple reproduction of the issue we are seeing.

**Comment by epicfaace** [comment]
@travisdahl no updates yet. Yeah the playground link is currently not working (https://github.com/mozilla-services/mozilla-services.github.io/pull/4), but just replace "react-jsonschema-form/" with "react-jsonschema-form" and it should work.

**Comment by heath-freenome** [comment]
@travisdahl Are you still having this problem with 5.x?
