### ISSUE TITLE
Integrate with code climate

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1180]
Regarding #1170

See https://docs.codeclimate.com/docs/travis-ci-test-coverage

**Comment by hwine** [comment]
@epicfaace this request needs to be approved by a repository admin before it can be granted.

Also, since we have not yet evaluated code climate, please supply information as outlined in [the wiki](https://wiki.mozilla.org/GitHub#How_do_I_hook_up_a_new_3rd_party_application_to_a_repository_in_the_mozilla_org.3F)

**Note**: code climate appears to be an old style OAuth application. That significantly raises the bar on our security review. If they have a "GitHub App" version, please submit that, or consider another vendor.

**Comment by epicfaace** [comment]
@hwine thanks for the info. Are there any other code analysis Github Apps that have already been evaluated and used at Mozilla?

**Comment by hwine** [comment]
We do have Codecov already enabled in 'mozilla' org, so it should be a quick review to enable that in 'mozilla-services'.

The other place to ask would be #github on irc -- I don't make any heavy use of GitHub myself, I just handle the administration. 😄
