### ISSUE TITLE
Nested dynamic schema dependencies

### ISSUE THREAD

**Issue by kalyan542** [rjsf-team/react-jsonschema-form#1217]
I have select box A which has options option1, option2
if select option1 in select box A,  populate another select box B with options NORMAL, CMC
If i select Normal in select box B, populate some fields name, age
If select CMC populate fields id, enable 

I can able to populate dependency fields based on select box A but not with select box B.

{
  type: "object",
  properties: {
    A: {
      "title": A,
      "type": "string",
      "enum": [
        "--select--",
        "option1",
        "option2",
      ],
      "default": "--select--"
    },
  },
  "dependencies": {
    "A": {
      "oneOf": [
        {
          "properties": {
            A: {
              "enum": [
                "option1"
              ]
            },
            B: {
              type: "string",
              title: B,
              enum: [
                "NORMAL",
                "CMC"
              ],
              enumNames: [
                "NORMAL",
                "CMC"
              ]
            },
            name: {
              type: "string",
              title: "name"
            },
            age: {
              type: "string",
              title: "age"
            },
          }
        },
      ]
    }
  }
}

**Comment by epicfaace** [comment]
@kalyan542 Can you please post a playground link (https://mozilla-services.github.io/react-jsonschema-form) demonstrating the issue? That will help us get to the problem faster.

**Comment by epicfaace** [comment]
@kalyan542 Can you please post a playground link (https://mozilla-services.github.io/react-jsonschema-form) demonstrating the issue? That will help us get to the problem faster.

**Comment by kalyan542** [comment]
Please see this below example.
https://jsfiddle.net/x598Lnvj/

**Comment by kalyan542** [comment]
> @kalyan542 Can you please post a playground link (https://mozilla-services.github.io/react-jsonschema-form) demonstrating the issue? That will help us get to the problem faster.

Added jsfiddle playground link

**Comment by epicfaace** [comment]
@kalyan542 What are you expecting? When I select "CMC" I get the following fields, which seems to accord with what the schema describes:

![image](https://user-images.githubusercontent.com/1689183/55264355-6b22a180-524a-11e9-8f00-9ac06383de9a.png)

**Comment by kalyan542** [comment]
only show **name** and **age** fields If i select CMC in Select box B
only show **id** and **enable** fields If i select NORMAL in Select box B

**Comment by epicfaace** [comment]
@kalyan542 Does this schema work for you? https://jsfiddle.net/jhocLqvb/

**Comment by kalyan542** [comment]
**B** select box has to show after **A** select box. if i add  uiSchema={uiSchema} for fields order getting this error "Invalid root object field configuration:uiSchema order list contains extraneous property 'B'."

**Comment by epicfaace** [comment]
That error should not come in the latest playground version, since #814 was merged: [Playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJBIjp7IkEiOiJvcHRpb24xIiwiQiI6IkNNQyJ9fSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkEiOnsidGl0bGUiOiJBIiwiJHJlZiI6IiMvZGVmaW5pdGlvbnMvQSJ9fSwiZGVmaW5pdGlvbnMiOnsibmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJOQU1FIn0sImFnZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJBR0UifSwiaWQiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiSUQifSwiZW5hYmxlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkVuYWJsZSJ9LCJBIjp7InRpdGxlIjoiQSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7IkEiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsiLS1zZWxlY3QtLSIsIm9wdGlvbjEiLCJvcHRpb24yIl0sImRlZmF1bHQiOiItLXNlbGVjdC0tIn19LCJkZXBlbmRlbmNpZXMiOnsiQiI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJCIjp7ImNvbnN0IjoiQ01DIn0sIm5hbWUiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvbmFtZSJ9LCJhZ2UiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvYWdlIn19fSx7InByb3BlcnRpZXMiOnsiQiI6eyJjb25zdCI6Ik5PUk1BTCJ9LCJpZCI6eyIkcmVmIjoiIy9kZWZpbml0aW9ucy9pZCJ9LCJlbmFibGUiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvZW5hYmxlIn19fV19LCJBIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7IkEiOnsiZW51bSI6WyJvcHRpb24xIl19LCJCIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkIiLCJlbnVtIjpbIk5PUk1BTCIsIkNNQyJdLCJlbnVtTmFtZXMiOlsiTk9STUFMIiwiQ01DIl19fX1dfX19fX0sInVpU2NoZW1hIjp7InVpOm9yZGVyIjpbIkEiLCJCIiwibmFtZSIsImFnZSIsImlkIiwiZW5hYmxlIl19fQ==). However, this fix has not been released in the latest version yet.

However, there seems to be another problem -- the ui:order is not being respected, probably because of something related to nested dependencies.

**Comment by ezzadeen** [comment]
This issue seems too old.
I'm using @rjsf/core": "^3.2.1. I don't have this problem.

`
{  "definitions": {
    "Root": {
      "type": "object",
      "properties": {
        "first_dependency": {
          "type": "string",
          "enum": ["yes", "no"]
        }
      },
      "dependencies": {
        "first_dependency": {
          "oneOf": [
            {
              "properties": {
                "first_dependency": {
                  "enum": ["yes"]
                },
                "properties": {
                  "title": "",
                  "type": "object",
                  "properties": {
                    "nested_dependency": {
                      "type": "string",
                      "enum": ["yes", "no"],
                      "default": "no"
                    }
                  },
                  "dependencies": {
                    "nested_dependency": {
                      "oneOf": [
                        {
                          "properties": {
                            "nested_dependency": {
                              "enum": ["yes"]
                            },
                            "properties": {
							}
						  }
						},
						{
                          "properties": {
                            "nested_dependency": {
                              "enum": ["no"]
                            },
                            "properties": {}
						  }
						}
					  ]
					}
				  }
                }
              }
            }
          ]
        }
      }
    }
  }
}

`

**Comment by nickgros** [comment]
Per @ezzadeen this seems to be fixed. Please open a new issue if any related issues persist.
