### ISSUE TITLE
Keys with the same name in different `anyOf` options break the form

### ISSUE THREAD

**Issue by jobchong** [rjsf-team/react-jsonschema-form#1244]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Keys with the same name in different options for `anyOf` resets the `anyOf` field to the first option when entering input into other options.

### Steps to Reproduce

1. Visit the playground
2. Select the `anyOf` example
3. Rename the `foo` key of the first option in the first `anyOf` example to `bar` (so it matches the key in the second option)
4. Add an Item, and select option 2
5. Enter any character into the `bar` field

#### Expected behavior

`formData` to show that I have added user input to `bar` for option 2, and that option 2 remains selected on the form

#### Actual behavior

`formData` is indistinguishable when inputting to `bar` for either option 1 or option 2, and the form resets to option 1

### Version

1.3.0

**Comment by jobchong** [comment]
I'm wondering if this issue is what [this particular FAQ](https://react-jsonschema-form.readthedocs.io/en/latest/#q-does-rjsf-support-oneof-anyof-multiple-types-in-an-array-etc) is referring to.

**Comment by epicfaace** [comment]
I don't think this issue is solely caused by two keys having the same name. [This schema](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpdGVtcyI6W3siYmFyIjoic2Rmc2RmIn1dLCJpZENvZGUiOiJiYXIifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFnZSI6eyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiQWdlIn0sIml0ZW1zIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJhbnlPZiI6W3sicHJvcGVydGllcyI6eyJiYXIiOnsidHlwZSI6Im51bWJlciJ9fX0seyJwcm9wZXJ0aWVzIjp7ImJhciI6eyJ0eXBlIjoic3RyaW5nIn19fV19fX0sImFueU9mIjpbeyJ0aXRsZSI6IkZpcnN0IG1ldGhvZCBvZiBpZGVudGlmaWNhdGlvbiIsInByb3BlcnRpZXMiOnsiZmlyc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkZpcnN0IG5hbWUiLCJkZWZhdWx0IjoiQ2h1Y2sifSwibGFzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiTGFzdCBuYW1lIn19fSx7InRpdGxlIjoiU2Vjb25kIG1ldGhvZCBvZiBpZGVudGlmaWNhdGlvbiIsInByb3BlcnRpZXMiOnsiaWRDb2RlIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IklEIGNvZGUifX19XX0sInVpU2NoZW1hIjp7fX0=) is fine, for example. The problem seems to be when you have two keys with the same name _and_ with the exact same schema (in your example, both having `{type: "string"}`).

Of course this needs to be fixed because having the same schemas in `anyOf` is still JSON schema-compliant, but @jobchong I'm wondering what exactly your use case is for having this type of schema? With having the same schemas in `anyOf`, you wouldn't be able to know which option the user selected anyway.

**Comment by epicfaace** [comment]
Looks like the issue that the FAQ is referring to is actually ##1204

**Comment by jobchong** [comment]
An option for an `anyOf` may be a superset of the other option, and both options belonging to the same type. For example:

```
{
    "Drivers_License": {
	"properties": {
            "idvalue": {
		"type": "string"
        },
	"title": "Driver's License Number",
	"type": "object"
    },
    "Passport": {
	"properties": {
            "country": {
		"type": "string"
            },
            "idvalue": {
		"type": "string"
            }
	},
	"title": "Passport Number",
	"type": "object"
    },
}
```

So to provide personal information to a form, a user may either choose to share his/her driver's license or passport number. We assume that if the user provides a driver's license number, he/she is domestic, but if a passport number is provided, we need the country where the passport is from.

We could work around this issue by renaming the `idvalue` properties of each option, but both options are `refs` to the same `ID` definition, and renaming would kind of defeat the purpose of a `ref`.

**Comment by epicfaace** [comment]
[Reproducible example of what you're referring to](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjb3VudHJ5IjoiZGYiLCJpZHR5cGUiOiJzZGYifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImFnZSI6eyJ0eXBlIjoiaW50ZWdlciIsInRpdGxlIjoiQWdlIn0sIml0ZW1zIjp7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJvYmplY3QiLCJhbnlPZiI6W3sicHJvcGVydGllcyI6eyJmb28iOnsidHlwZSI6InN0cmluZyJ9fX0seyJwcm9wZXJ0aWVzIjp7ImJhciI6eyJ0eXBlIjoic3RyaW5nIn19fV19fX0sImFueU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImlkdHlwZSI6eyJ0eXBlIjoic3RyaW5nIn0sImlkdmFsdWUiOnsidHlwZSI6InN0cmluZyJ9fSwidGl0bGUiOiJEcml2ZXIncyBMaWNlbnNlIE51bWJlciIsInR5cGUiOiJvYmplY3QifSx7InByb3BlcnRpZXMiOnsiY291bnRyeSI6eyJ0eXBlIjoic3RyaW5nIn0sImlkdHlwZSI6eyJ0eXBlIjoic3RyaW5nIn0sImlkdmFsdWUiOnsidHlwZSI6InN0cmluZyJ9fSwidGl0bGUiOiJQYXNzcG9ydCBOdW1iZXIiLCJ0eXBlIjoib2JqZWN0In1dfSwidWlTY2hlbWEiOnt9fQ==)
