### ISSUE TITLE
additionalProperties form - enum for key

### ISSUE THREAD

**Issue by mklokocka** [rjsf-team/react-jsonschema-form#1250]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Would it be possible to add a feature that would enable the user to set a given set of all possible keys of `additionalProperties`?

At the moment, I validate the keys with `propertyNames` which works, but it would be much cleaner for the user to have it set as an enum.

#### Expected behavior

`additionalProperties` are rendered with a dropdown key selection if enum given.

#### Actual behavior

`additionalProperties` have to options for key customizations and `propertyNames` are ignored in the rendering phase (but used for validation).

### Version

Latest.

**Comment by glasserc** [comment]
How would this work from a JSON Schema perspective? `additionalProperties` doesn't really have any way to express restrictions on the property names. `propertyNames` does, but it doesn't just affect properties that are validated against `additionalProperties`; it also affects those that fall under `properties` or `patternProperties`.

**Comment by bmschmidt** [comment]
Not the OP, but as it happened was just googling for almost this same issue. My expected behavior was that, when there is a constraint on property names, the interface elements will use dropdowns for the keys to any additionalProperties. 

For example, in the following schema, when you add another property to the array with a plus button, the values of the properties give you a dropdown to choose from "val1" and "val2", but you just get a text field to write into without any hints about permitted values are. Instead, it should be a dropdown to choose from 'foo' or 'bar.' 

```json
{
  "type": "object",
  "propertyNames": {
    "enum": [
      "foo",
      "bar"
    ],
    "type": "string"
  },
  "additionalProperties": {
    "type": "string",
    "enum": [
      "val1",
      "val2"
    ]
  }
}
```

Great library, thanks for your work.

**Comment by mklokocka** [comment]
@bmschmidt This is exactly something I had in mind.

**Comment by epicfaace** [comment]
@bmschmidt that behavior makes sense -- would you be able to make a PR implementing this?

**Comment by bmschmidt** [comment]
Sorry, afraid I can't help--I don't know anything about React. (I actually am using React for the first time just for this library.)
