### ISSUE TITLE
Jalali or Persian datetime picker

### ISSUE THREAD

**Issue by MohsenZamany** [rjsf-team/react-jsonschema-form#1328]
i want a persian-jalali date picker instead of gregorian datepisker

**Comment by epicfaace** [comment]
You'd probably need to make a custom widget for that. You could make a widget and then make a PR for it if you'd like to add it to the main library.

**Comment by jorenvh1** [comment]
I am also interested in a persian-jalali datepisker.

**Comment by loganvolkers** [comment]
Here's an [example](https://codesandbox.io/s/test-jalali-react-datepicker-guouv) based on a [custom widget](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-widget-components) and this [random library](https://github.com/rzkhosroshahi/react-jalali-datepicker) that I found.

Unfortunately, this example does not work, since that library is not a stateless component.
