### ISSUE TITLE
Validations not working properly in Schema dependencies

### ISSUE THREAD

**Issue by gr8pathik** [rjsf-team/react-jsonschema-form#1377]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/gr8pathik/9ynhgatz/) demonstrating the issue.

### Description
I am using schema dependencies in the form. I have one drop-down which has two values `cat 1` and `cat 2`. If I select `cat1` I have to display two fields (`subcat and type`) and if I select `cat 2` i have to display one field (`type`).  `type` is a multiple checkbox widget. When a form is first rendered, we have some data in `formData`. Eg. So in `formData` we have `cat1`, `subcat1` and `type` with two values `[type1, type2]`. Now when you change `cat2` from the first dropdown you can see only `type` widget which is correct. Now select some value in `type` widget like `type 4` and `type 5` and submit the form. It will give the error.

Why It is giving an error, because of the first time in `formData` in `type` field there were two values and when I select a type value from `cat2` drop down it will **append** the type in `formData` but should **replace** with the new value.

### Steps to Reproduce

1. [First Step]
[Open JSFiddle](https://jsfiddle.net/gr8pathik/9ynhgatz/). Select `Category 2` from the Category dropdown.
2. [Second Step]
Now select type. Like: `Type 4` and `Type 5`
3. [and so on...]
Now submit the form. I will give an error.

#### Expected behaviour

It should not give an error.

#### Actual behavior

It is giving an error.

### Version

`"react-jsonschema-form": "^1.7.0"`

**Comment by epicfaace** [comment]
I think this is related to #1357.

**Comment by epicfaace** [comment]
@gr8pathik I can see how this is considered a bug when `omitExtraData` and `liveOmit` are both true -- because then data will be omitted from dependencies. (which is what I reported in #1357)

However, by default, the form does not have omitExtraData / liveOmit set to true. This is what allows, say, someone to show a textbox through a dependency, enter in the value for a dependency, then hide the textbox, but the value still persists. It seems like this is expected behavior for the form -- even in the bug you reported, the form technically _does not omit extra data_, which is expected.

That being said, maybe it's better to actually omit extra data in cases like these (in which you alternate between two dependencies with the same key, but with different schemas). Do you think that might be a reasonable default?

**Comment by Rolorob** [comment]
We are experiencing the same issue. We think it is a good idea to omit the extra data in cases like these, when you alternate between two dependencies with the same key, but with different schema's.

Especially because they are part of a OneOf, you should never want more than one item.

**Comment by epicfaace** [comment]
The question is -- is it better to omit _all data_ or omit just _extra data_ when alternating between two dependencies with the same key, but with different schemas? I can think of valid use cases for either option.
