### ISSUE TITLE
Selector not working inside dependency for uncontrolled components

### ISSUE THREAD

**Issue by snirp** [rjsf-team/react-jsonschema-form#1394]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The select input inside a schema dependency is not working as intended. The default value is ignored and it is not possible to select a single choice. When there are multiple choices, the workaround is to first change the value and then back to the initial.

### Steps to Reproduce

This is best viewed in the provided sample: https://codesandbox.io/s/github/snirp/schemadebug

* **Form A**: inside "select2" the value of "option2A" is displayed, but this value is not actually selected. Only "select1" is actually submitted and no validation errors are triggered (although "select2" is a required field. Toggling between "option2A" and "option2B" can be used as a workaround.

* **Form B**: the same issue, but the workaround is not available, since there are no choices to toggle between. This is a particularly nasty situation we encountered.

* **Form C**: the defaults are provided through `formData`. This is the workaround we are using.

#### Expected behavior

Should work just as select input outside the dependency

#### Actual behavior

See the provided codesandbox

### Version

^1.7.0

**Comment by epicfaace** [comment]
How are you determining that "option2A" is not selected? For me, it seems like it is both showing up and part of the form data.

![image](https://user-images.githubusercontent.com/1689183/62817933-c0719800-baf3-11e9-94da-1d94183a36bd.png)

**Comment by snirp** [comment]
There are two ways to observe that "option2A" is not selected.
 
1) When you submit the form, the formData is logged as:

```
{ select1: "option1A" }
```

2) The schema dependency, containing "val2A", is not showing. Observe that toggling between "option2B" and "option2A" changes this, but there is not way to do so in FORM2

**Comment by snirp** [comment]
@epicfaace - does this answer your question and should this issue be tagged as a bug?

**Comment by epicfaace** [comment]
@snirp thanks for the explanation, makes sense. When I go to [this playground link](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzZWxlY3QxIjoib3B0aW9uMUEiLCJvcHRpb24xQSI6eyJzZWxlY3QyIjoib3B0aW9uMkEiLCJvcHRpb24yQSI6e319fSwic2NoZW1hIjp7InByb3BlcnRpZXMiOnsic2VsZWN0MSI6eyJ0eXBlIjoic3RyaW5nIiwiZGVmYXVsdCI6Im9wdGlvbjFBIiwiZW51bSI6WyJvcHRpb24xQSJdfX0sImRlcGVuZGVuY2llcyI6eyJzZWxlY3QxIjp7Im9uZU9mIjpbeyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJvcHRpb24xQSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJzZWxlY3QyIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0Ijoib3B0aW9uMkEiLCJlbnVtIjpbIm9wdGlvbjJBIiwib3B0aW9uMkIiXX19LCJkZXBlbmRlbmNpZXMiOnsic2VsZWN0MiI6eyJvbmVPZiI6W3sidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsib3B0aW9uMkEiOnsicmVxdWlyZWQiOlsidmFsMkEiXSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsMkEiOnsidHlwZSI6InN0cmluZyJ9fX0sInNlbGVjdDIiOnsiY29uc3QiOiJvcHRpb24yQSJ9fX0seyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJvcHRpb24yQiI6eyJyZXF1aXJlZCI6WyJ2YWwyQiJdLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ2YWwyQiI6eyJ0eXBlIjoic3RyaW5nIn19fSwic2VsZWN0MiI6eyJjb25zdCI6Im9wdGlvbjJCIn19fV19fSwicmVxdWlyZWQiOlsic2VsZWN0MiJdfSwic2VsZWN0MSI6eyJjb25zdCI6Im9wdGlvbjFBIn19fV19fSwicmVxdWlyZWQiOlsic2VsZWN0MSJdLCIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIn0sInVpU2NoZW1hIjp7fX0=) it is working fine, but that is because `Form` in the playground is a controlled component (with `formData` and `onChange` props passed in). So it seems like this issue only happens for uncontrolled components.

**Comment by epicfaace** [comment]
#1371 fixed a similar issue, but it must not have caught everything.

**Comment by snirp** [comment]
The playground seems to handle it fine. I tried to make it a controlled form myself by using the state as the `formData` and updating state from `onChange`, but that makes no difference. How does the playground do it?

**Comment by epicfaace** [comment]
> The playground seems to handle it fine. ~I tried to make it a controlled form myself by using the state as the `formData` and updating state from `onChange`, but that makes no difference. How does the playground do it?~
> 
> edit: it does work as a controlled form: https://codesandbox.io/s/schemadebug-uqfq6

Yeah, the form on the playground is already a controlled form.
