### ISSUE TITLE
Consider changing default value for additionalProperties: true

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#1411]
A form with `additionalProperties: true` has a default value of "New Value". Should we consider changing this (maybe to an empty string)?

https://github.com/mozilla-services/react-jsonschema-form/blob/310b8a5309bd55fd1c3e1533c93b3ce135b03dda/src/components/fields/ObjectField.js#L166

**Comment by v1vendi** [comment]
But default value is not exactly "New Value", but is based on value type, so I think this behavior might be correct

**Comment by minelminel** [comment]
I'm currently dealing with a use case where I am allowing additionalProperties to be included which represent key-value property pairs. I have the field type set to `object` which correctly inserts these pairs when I click the button, however I have seemingly no control over the default _value_ of these field pair contents. Preferably I'd like if they were inserted as _empty_ string fields which would allow my placeholder text to be shown instead of the funky "New Value-1" convention. Thoughts?

**Comment by epicfaace** [comment]
Yeah, I think an empty string field makes a lot of sense. Would you be up to making a PR that does this?
