### ISSUE TITLE
Don't display submit button

### ISSUE THREAD

**Issue by dreadheadsic** [rjsf-team/react-jsonschema-form#1602]
Right now the only way to not display submit button is to provide children to the form, so when i want to skip the submit button and submit form programatically i pass empty fragment as a children to the form. Should there be an option to skip rendering submit button?

**Comment by epicfaace** [comment]
Sure, would accept a PR that adds an option to do that -- it would be kind of in the same vein as #1093.

**Comment by dreadheadsic** [comment]
Cool, i'll see what i can do.

**Comment by erhuz** [comment]
I would really need this feature! :+1:
Any update @dreadheadsic ?

**Comment by sbusch** [comment]
Altough we hide the submit button, too, I'm against adding features if aren't really necessary. So I personally would vote against an additional prop like `hideSubmitButton` just for hiding the button. Alternative to an empty fragment is passing `null` to children, `Form` can then be self-closing:

```javascript
<Form
  // ...
  children={null} // hide the submit button
/>
```

Could be added to the [FAQ](https://react-jsonschema-form.readthedocs.io/en/latest/#faq).

But I'm fine with having a new prop, e.g. `submitButton` as an *alias* for `children`, to make the API clearer. Note: there may be a value for `submitButton` **and** `children`.

To have an additional benefit, this could be extented into support for passing functions (render prop).

**Comment by dreadheadsic** [comment]
@sbusch passing `children={null}` will not hide submit button.

**Comment by sbusch** [comment]
@dreadheadsic yes, [you're right](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/Form.js#L399). Don't know why my test was successful...

Passing `children={true}` should do the job.

**Comment by dreadheadsic** [comment]
@sbusch haha, i see, yet another hack. That just doesn't feel right. What would you think if you're looking at some code and find component that says `children={true}`?

**Comment by epicfaace** [comment]
What was wrong with passing in an empty fragment as a children to a form, again? It does look intuitive when someone reads the code.

Aliasing children as submitButton _might_ work, but rather than as a prop, it might be good to put it as part of an overall generic theme configuration as I detailed in https://github.com/rjsf-team/react-jsonschema-form/issues/1222#issuecomment-511054781

**Comment by dreadheadsic** [comment]
Now that's a good question. I don't mind passing empty fragment as a children, and it does indeed looks intuitive. Thing is that it's not so clear in docs how to do this, so at least documenting this so it's easy to find will be enough.

**Comment by mirajp** [comment]
Suggestion: if the `onSubmit` property is not specified, it should hide the submit button. That seems like the most direct thing to do as a user. This is how I control the custom children buttons for my rjsf wrapper and I haven't come across a downside to this approach yet.
Precedence: if you do not want to subscribe to the change events as a user types in values, you simply don't set the 'onChange' property on the Form.

**Comment by vidjuheffex** [comment]
Yes, but you still may might want to have an onSubmit AND not display the button.

(i.e. rely on enter press or programmatic use only)

The two most sensible options I see are adding a prop: 'hideSubmitButton' (I think the best approach _would_ be to hide it, so all accessibility behavior is retained), or having the `submitRow` be a field and `submitButton` be a widget that can be customize using the same intuitive system that exists for all other widgets.

I  imagine most people are disabling simply because it's not where they want it and it can be easier to hide it then to css your way to the goal.

**Comment by zhaoyao91** [comment]
```
<Form>
  <Fragment />
</Form>
```

**Comment by jacqueswho** [comment]
@epicfaace I was just about to log an enhancement regarding the submit button. was thinking we have submitButtonProps to give options. This includes hiding, changing text, shape, use icons. I see some of the themes are creating their own submit button as children. But because no props are being passed down to the children, the themes cant make use of the hide or change text props. This also allows for later other optional props related to the submit button.

**Comment by epicfaace** [comment]
@jacqueswho yeah, submitButtonProps sounds like a good idea -- perhaps we call it `ui:submitButtonProps`?

**Comment by jacqueswho** [comment]
> @jacqueswho yeah, submitButtonProps sounds like a good idea -- perhaps we call it `ui:submitButtonProps`?

@epicfaace yes, was thinking the same thing. so just need to agree on options to pass. Is this already logged somewhere else. 
```JS
{
  'ui:submitButtonProps':{
      showButton: true,
      buttonText: 'submit',
      
   }
}

```

**Comment by ronnyek** [comment]
This one seems kind of liek a no brainer... is this somethign we can expect anytime soon? Tossing a form in a modal, and want to use my modals buttons to handle actually doing work.

**Comment by epicfaace** [comment]
> ```
> <Form>
>   <Fragment />
> </Form>
> ```

@ronnyek you can get this done this way.

**Comment by bradleymarques** [comment]
I got this to work by explicitly passing a child element:

```react
<Form schema={...}>
  {!disabled && <div>Submit Button</div>}
  {disabled && <div></div>}
</Form>
```

**Comment by linonetwo** [comment]
This will work too:

```
.rjsf > div > button.btn {
  display: none;
}
```

**Comment by navono** [comment]
<Form schema={SCHEMA.schema} formData={formData} onChange={this.onFormDataChange} onSubmit={this.onSubmit}>
          <React.Fragment />
          <Button type="primary" htmlType="submit" className="login-form-button">
            Log in
          </Button>
        </Form>

**Comment by SeanNexusVisa** [comment]
Giving it a disabled button is also a way.

<Form schema={schema} iSchema={uiSchema} formData={formData}>
    <Button disabled variant="contained" style={{ marginTop: "24px" }}>
        SUBMIT
    </Button>
</Form>

**Comment by fregante** [comment]
This this is at the top of google searches, here's a modern solution:


```jsx
<Form
  uiSchema={{
    "ui:submitButtonOptions": { norender: true },
  }}
/>
```

https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema#submitbuttonoptions

**Comment by zunnur-trinovik** [comment]
> This this is at the top of google searches, here's a modern solution:
> 
> ```js
> <Form
>   uiSchema={{
>     "ui:submitButtonOptions": { norender: true },
>   }}
> />
> ```
> 
> https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema#submitbuttonoptions

By Far, the best solution that makes the code more readable and understandable.
