### ISSUE TITLE
Updates in the formData are showing "lagged"

### ISSUE THREAD

**Issue by tomaszmys** [rjsf-team/react-jsonschema-form#1613]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

My situation requires maintaining formData state in a component wrapping the react-jsonschema-form (<Form>), and passing it back to <Form> to render (much like it's done to the schema and uiSchema in the "advanced conditional fields" example - https://jsfiddle.net/cowbellerina/zbfh96b1/).
The updated data, however, is not shown in the form until ANOTHER change within the form is made. So, if we'd like to calculate the value of a field B, based on the another field A (e.g. as a^2), results are misleading:
- enter "1" in A => no update in B
- enter "2" in A => B gets set to "1"
- enter "3" in A => B gets set to "4"
- enter "4" in A => B gets set to "9"

### Steps to Reproduce

1. Open the "advanced conditional fields" example (https://jsfiddle.net/cowbellerina/zbfh96b1/)
2. Add a new line to the handleChange function:
```
    handleChange (data) {
        const schema = { ...this.state.schema };
        const uiSchema = { ...this.state.uiSchema };
        const { formData } = data;
	// vvvvv
        formData.city = formData.state+" the city";
        // ^^^^^

        const newState = processForm(originalSchema, originalUISchema, schema, uiSchema, formData);

        this.setState(newState);
    }
```
3. Run the changed code
4. Select "US", and select State "Alabama", then change the Selection to "Arizona"

#### Expected behavior

Field City gets its value set to "AL the city" first, then to "AZ the city"

#### Actual behavior

Field City first gets no update, then gets its value set to "AL the city" (while Arizona is already selected)

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by RoboPhred** [comment]
This is because you are trying to directly modify the formData, and not telling anything that you changed the property.  React does not know your property has changed, as there is no way to observe changes to objects.  You should always avoid changing property objects directly and instead clone the object, apply your new data, and pass it back to the component.

Create a new formData based on the incomming one, set your city there, and pass it back to the formData property of the Form.

For more information, read up on the [official react documentation](https://reactjs.org/docs/components-and-props.html#props-are-read-only) about properties.

**Comment by tomaszmys** [comment]
I didn't expect Form to use deep comparison to determine if the internal state needs to be updated, but - if you'd look at the example closely - a new object is already passed on each update (newFormData is created by assign within the processForm).
To double-check, I've modified the render function, to make sure a new object is passed to Form, but that did not solve the problem:
`    render () {
        return (<Form
                schema={this.state.schema}
                uiSchema={this.state.uiSchema}
                // vvvvv
                formData={Object.assign({}, this.state.formData)}
                // ^^^^^
                onChange={this.handleChange.bind(this)}
            />);
    }`

How exactly would you suggest to work around this?

**Comment by RoboPhred** [comment]
Rather than modifying the instance RJSF gives you, create a new instance and modify that.  This avoids changing the original state object which is deep compared against.

```js
    handleChange (data) {
        const schema = { ...this.state.schema };
        const uiSchema = { ...this.state.uiSchema };
        let { formData } = data;
	// vvvvv
        formData = {
          ...formData,
          city: formData.state + " the city";
        }
        // ^^^^^

        const newState = processForm(originalSchema, originalUISchema, schema, uiSchema, formData);

        this.setState(newState);
    }
```

You will need to deep clone the object anywhere you want to modify a property.  For example, if we were modifying formData.first.second, we would need to do
```js
  formData = {
    ...formData, // copy top-level props of formData
    first: { // override the 'first' key of our copy.
      ...formData.first, // Copy in the other props of formData.first
      second: "new value" // Override the 'second' property in our copy of 'first'
    }
```

Once you do this, you can remove the Object.assign cloning on render.
In general, it is a good idea not to actively clone things on render, as it will force the form to re-render every time your parent does.
(Mind you, Form currently does this anyway, but its a bug.  See #1631).

For really deep properties, you can use lodash/fp to automate this process.  It is included with the basic "lodash" npm package.
```js
import { set } from "lodash/fp"; // Important: "lodash/fp", just "lodash" won't do what we need.

  handleChange(data) {
    let formData = data.formData;
   // fp set arguments are (pathArray, value, target)
  // It selectively deep clones only what it needs to set the new value
    formData = set(["firstProp", "secondProp" "thirdProp"], "my new value", formData);
   this.setState({ formData });
  }
```

**Comment by tomaszmys** [comment]
Thank you, that was exactly what I've missed previously.

A shallow copy, created by `Object.assign()` does not suffice. I've found a solution most suitable for my case in `cloneDeep` (in lodash, as well). It has to be used with care not to cause performance issues, but the `formData` updates made outside of RJSF (and passed into the component) are now rendered properly.
