### ISSUE TITLE
Troubles with the new Playground

### ISSUE THREAD

**Issue by erunion** [rjsf-team/react-jsonschema-form#1630]
I'm running into a host of problems with the new Playground setup that's made local development impossible.

Running `npm start` from within `packages/playground` greets me with compilation errors like:

```
ERROR in ./src/index.js
Module not found: Error: Can't resolve '@rjsf/core' in '/Users/jon/code/react-jsonschema-form/packages/playground/src'
 @ ./src/index.js 18:0-45 360:29-33 384:29-33 544:23-32 626:21-30 682:29-33
 @ ./playground/app.js
 @ multi webpack-hot-middleware/client?reload=true ./playground/app
```

Running the same from within `packages/core` I get:

```
ERROR in ./playground/app.js
Module not found: Error: Can't resolve '@rjsf/playground' in '/Users/jon/code/react-jsonschema-form/packages/core/playground'
 @ ./playground/app.js 3:0-42 10:27-37
 @ multi webpack-hot-middleware/client?reload=true ./playground/app
```

I've run `npm run bootstrap` from the root directory but still can't get it booted. I am running the most current `master`.

Am I doing something wrong?

**Comment by Saulzi** [comment]
I had a ton of issues with regards to this, it is broken but for local development I did the following which works.

change reference to jsonschema-form in package.json of playground to reference local files in core i.e. 

`"react-json-schema-form": "file://../core"
`

this may also need changing in index.js back to react-jsonschema.form in import as @epicfaace' s recent commit changed this then run npm build:lib in core and start in playground..

don't push this change in PR as it will fail to build in CI.

I have wasted more than a day because of this not working properly, in my mind the lerna etc configuration is not there yet.

This is how I have been able to test my fixes in https://github.com/rjsf-team/react-jsonschema-form/pull/1610

**Comment by epicfaace** [comment]
@erunion hmm... I just tried cloning the repository again locally and it seemed to work for me. The changes to the playground were designed to make the local playground setup the same as before -- i.e., you just need to cd into the core directory and run `npm start` to run the playground. Here are the steps I followed:

```
cd packages/core
npm install
npm start
```

**Comment by Saulzi** [comment]
@epicfaace I have just pulled my latest for #1610 onto a new machine and it gives the old playground, i.e. the currently published to npm version, 

so yes it woks but not latest, likewise when I was working on #1610 I had real issues with changes not appearing in the playground which Is the same issue whtih I believe @erunion is having.

In my opinion there should only be one playground, i.e. nothing relating to the playground in core and it should have all of your latest changes to both the playground and core to aid development, this is currently not the case as there is devserver.js and few playground files in core and reference in package.json and references to core etc in package.json, there is a lot of cruft in both package.json and issues relating to the new seperated style here also, sourcemaps also need to work properly in the playground, i.e. the whole build here needs to be fixed, as this will really aid development with people using it as a traditional test harness (alongside tdd script)

**Comment by Saulzi** [comment]
@erunion please see @epicfaace 's pr #1639

**Comment by erunion** [comment]
Yeah so the instructions in https://github.com/rjsf-team/react-jsonschema-form/pull/1639 work to get a local playground running, but making changes with `packages/core` doesn't trigger Webpack builds.

I can use something like [npm-watch](https://www.npmjs.com/package/npm-watch) to look for changes to `src/` and re-run `npm run dist`, but that is just a messy solution.

This entire local development process right now is just fundamentally broken.

**Comment by epicfaace** [comment]
Right -- I hadn't realized that `packages/core` doesn't trigger Webpack builds. My bad, should have made an issue to discuss development setup with multiple packages before going ahead and implementing what I did.

I think an approach like what's mentioned in https://github.com/rjsf-team/react-jsonschema-form/pull/1639#issuecomment-596596398 might fix this problem. We use a single playground that we run from the `packages/playground` directory, and we use `npm link` so that the playground uses the local development version of `packages/core`. We can also run a build script as in #1606 that watches files in `packages/core` and recompiles them whenever changes are made. This should live-reload the playground properly. What do you think?

**Comment by erunion** [comment]
That should work! Though instead of having to use `npm link` you can probably just do `npx lerna bootstrap` since the monorepo is managed through Lerna already.

**Comment by Saulzi** [comment]
Exactly.... don't you mean mangled using lerna 😄 I have a branch with essentially the one playground to rule them all working (except the additional theme is broken) @epicfaace 's branch seems to have additional changes so I look forwards to less frustration when @epicfaace is done 👍

**Comment by erunion** [comment]
Closing this out because it should be resolved with https://github.com/rjsf-team/react-jsonschema-form/pull/1606.
