### ISSUE TITLE
Handle FiberNode objects in deepEquals

### ISSUE THREAD

**Issue by RVEIII** [rjsf-team/react-jsonschema-form#1693]
I'm working on a large project that targets React 16.12.0.  As of React 16, the React's core architecture is being reimplemented as React Fiber.  Using RJSF 1.8.1, I'm running into a problem with schemas displayed in expand panels where the app freezes up in trying to expand the expand panels.  It is freezing because Form.js shouldComponentUpdate ends up doing a deepEquals that recurses through FiberNodes...which in their nature are recursive objects with parents and siblings.  I have not seen it break out of this because I believe it ends up in an infinite loop.

You'll have to forgive my lack of a JSFiddle example as I'm unable to change the versions of React to replicate this scenario.

Workaround: Removing the shouldComponentUpdate method from Form.js eliminates the issue.  I have not noticed a degradation in performance by doing this either.  It seems like one of the main reasons for React Fiber is performance, so maybe letting React render and compare node trees is much better performance wise than it had been.  

Good React Fiber links:
https://github.com/acdlite/react-fiber-architecture
https://blog.ag-grid.com/inside-fiber-an-in-depth-overview-of-the-new-reconciliation-algorithm-in-react/

### Version
1.8.1 and 2.0.0-alpha.1

**Comment by Klynger** [comment]
Any updates here? I'm having the same problem

**Comment by Klynger** [comment]
I believe this is happening only when the `children` of `props` and `nextProps` are equal because of what @RVEIII said about FiberNodes, having this in mind, would it be a problem if `shouldRender` ignored internals of FiberNode inside of `children` by passing a flag to `deepEquals`? It seems to make sense ignore private properties of objects in a equals function and since all FiberNodes and objects in javascript properties in general are marked with `_` at the beginning of the name, I think it would be easy to add this check in the `deepEquals` function. And maybe add a condition to explicitly say to ignore private fields.

What do you think @epicfaace ?

**Comment by olzraiti** [comment]
This bug is still present. If `Form` gets `children` in `props`, the deep equality check in `Form`'s `shouldComponentUpdate` causes a total freeze since it starts There's something weird about it - I can repro it only in a production build. Maybe the React Fiber stuff works a bit different in production?

I don't think doing a deep equality checks helps performance wise. Probably the opposite... React's default shallow prop comparison should be enough.

Related discussion in Stack Overflow: https://stackoverflow.com/questions/72694275/lodash-isequal-function-is-causing-application-freeze

**Comment by fregante** [comment]
We're seeing this issue with RJSF 5.14.1 when passing a plain empty `<div/>` as a child to `<JsonSchemaForm>`, but only during development. React 17

**Comment by fungairino** [comment]
We also ran into this bug and had to work around it by passing `true` to the children props since we also didn't want the default submit button to be rendered.
