### ISSUE TITLE
Material UI theme problem with initial false boolean

### ISSUE THREAD

**Issue by DennisKuhn** [rjsf-team/react-jsonschema-form#1796]
Kia Ora :-)
thanks for the awesome library :-)

### Description
If a required boolean property is loaded, e.g. formData with `test: false`, it is not recognised as having a value. When clicking submit, it shows the error: _Please tick this box if you want to proceed_.

_schema.json:_
```
{
  "type": "object",
  "properties": {
    "test": {
      "type": "boolean"    
    }
  },
  "required": ["test"]
}
```

_formData.json:_
```
{
  "test": false 
}
```

_uiSchema.json:_
`{}`

#### Expected behavior
Allows to submit with initial false-boolean[Playground default-theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0IjpmYWxzZX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InR5cGUiOiJib29sZWFuIn19LCJyZXF1aXJlZCI6WyJ0ZXN0Il19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==)

#### Actual behavior
Shows error on submit with initial false-boolean[Playground material-ui-theme](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0IjpmYWxzZX0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJ0ZXN0Ijp7InR5cGUiOiJib29sZWFuIn19LCJyZXF1aXJlZCI6WyJ0ZXN0Il19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoibWF0ZXJpYWwtdWkiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

## Version
Playground as of 2020-06-01
@rjsf/core@2.0.1
@rjsf/material-ui@2.0.1

@material-ui/core@4.9.10
react@16.13.1

Anything I can do?
Dennis

**Comment by stanlemon** [comment]
This isn't specific to the material theme. This behavior is the same in the default theme. I'm not sure that this is a bug either...? If you specify `"default": false` on the schema I believe you'll get the behavior you're seeking.

**Comment by koosham** [comment]
@DennisKuhn I think this behavior is because of Html 5 validation on the boolean input. Specifying `required` in boolean `input` of html forms ensures checkbox is checked (as in "I agree to terms" checkboxes you will see everywhere).
That being said, it appears that the Material UI theme translates the `required` in the JSON schema to a `required` in the `input` tag of some html `form`. Therefore, putting the `"required": ["test"]` in your schema, although is needed to ensure that form data contains `test`, will have this side effect.
If you try with `noHtml5Validate={true}` (see [here](https://react-jsonschema-form.readthedocs.io/en/latest/api-reference/form-props/#nohtml5validate)) or if you remove `"required": ["test"]` from your JSON schema, the pop up will not show anymore.
I don't know how to fix the problem, but will check on that.

**Comment by koosham** [comment]
@DennisKuhn @stanlemon it appears to me that the issue is due to the lack of `schemaRequiresTrueValue` function in [material-ui implementation of checkbox](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/CheckboxWidget/CheckboxWidget.tsx) while such function exists in [the core](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/widgets/CheckboxWidget.js). In the material ui code, `required` is passed from `props` to the `Checkbox` directly (lines 12 and 33 of CheckboxWidget.tsx)

**Comment by stanlemon** [comment]
Good find! 🤔 

I think what needs to be done here is to extract `schemaRequiresTrueValue()` into utils, and then it can be used in the Material UI theme and others as they are developed.  We probably need a different name for then schemaRequiresTrueValue, maybe something particular to the checkbox, I'm not sure (names are hard). We'll need a new covering test as well since we're exposing this to other use cases.

@koosham any interest in submitting a PR? If not, no worries I can put something together.

**Comment by koosham** [comment]
@stanlemon well I tried doing what you said and it seems to be working fine in the playground (see my changes in [this commit](https://github.com/koosham/react-jsonschema-form/commit/e7cf8c0f4bcf0212d9230848d1176f78e70e061f) on my forked repo). I'm not good with names, so I kept the same function name for now. Also very busy right now, so unfortunately I can't work on the tests either. If you don't mind taking care of this issue, it would be great.
