### ISSUE TITLE
No min, max, or step in MaterialUI UpDown component

### ISSUE THREAD

**Issue by matthias-ccri** [rjsf-team/react-jsonschema-form#2022]
### Description

The library has support for setting the input[type=number] min, max, and step attributes via minimum, maximum, multipleOf. From the [Widgets page](https://react-jsonschema-form.readthedocs.io/en/docs/usage/widgets/#for-number-and-integer-fields):

> If JSON Schema's `minimum`, `maximum` and `multipleOf` values are defined, the `min`, `max` and `step` input attributes values will take those values.

I'm seeing that the 'updown' widget does not support these attributes.

[Codesandbox](https://codesandbox.io/s/frosty-thompson-0o88w?file=/src/App.tsx)

#### Expected behavior

The UpDown input should step by 3, and bound at 1 and 10.

#### Actual behavior

The UpDown input steps by 1, and does not bound at any min or max.

### Version

2.3.0

**Comment by zmagauina-fn** [comment]
I'm having a problem with this too. The fix for this is pretty simple and I'm happy to do it. 
The changes would look very similar to [this PR](https://github.com/rjsf-team/react-jsonschema-form/pull/2114), but for Material UI you need to put the `stepProps` value as generated from that PR into the `inputProps` property of the Material UI `Input` component:
```
<Input
        id={id}
        autoFocus={autofocus}
        required={required}
        type="number"
        disabled={disabled || readonly}
        value={value ? value : ''}
        onChange={_onChange}
        onBlur={_onBlur}
        onFocus={_onFocus}
        inputProps={stepProps}
      />
```
@epicfaace

**Comment by heath-freenome** [comment]
Fixed in v5 beta
