### ISSUE TITLE
React 17 submit event not bubbling

### ISSUE THREAD

**Issue by dreadheadsic** [rjsf-team/react-jsonschema-form#2104]
Because of the changes in way [react 17 attaches event listeners](https://reactjs.org/blog/2020/10/20/react-v17.html#changes-to-event-delegation), submitting the form programatically no longer works because submit event doesn't bubble.
Solution for this would be to add `bubbles: true` when dispatching CustomEvent submit.

**Comment by epicfaace** [comment]
Thanks, would you be able to make a PR to fix this?

**Comment by dreadheadsic** [comment]
sure, why not, it's a one liner.

**Comment by timothyallan** [comment]
Applied the PR manually and it fixes a bunch of headaches for us, thanks! Will it be pushed to a release soon in case we forget to update manually again?

**Comment by shanemiller89** [comment]
Same as above, fix works great, appreciated! Also wondering if this will be pushed to release soon?

**Comment by epicfaace** [comment]
See @dreadheadsic 's comment (https://github.com/rjsf-team/react-jsonschema-form/pull/2105#issuecomment-731785759), this issue doesn't appear to be a problem with rjsf but rather caused by inadvertently running two different React versions at the same time. Does that fix it for any of you @timothyallan @shanemiller89 ?

**Comment by timothyallan** [comment]
This is happening to us on a fairly large production SPA. If we were running multiple versions of React, I would hope that we'd be aware of it :)

**Comment by shanemiller89** [comment]
Same, we are using this on a stand alone SPA. We were only running React v. 17.01

**Comment by dreadheadsic** [comment]
@timothyallan @shanemiller89 react-jsonschema-form's peerDependency is react 16 so whatever version is your app using, rjsf will use 16, therefore the issue with two versions.
You can test this by cloning this repo, change peerDependency to react 17 and use it inside your app.
Please correct me if i'm wrong. @epicfaace

**Comment by shanemiller89** [comment]
Yep, changing the peerDependency to react 17 does fix the issue. 

We will run a forked version until rjsf is updated.

Thanks for the assist y'all :+1:

**Comment by epicfaace** [comment]
Hmm, I'm a bit confused -- I thought the peerDependency is set to `>=16`? (see https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/package.json#L41-L43)

I would have thought that that would mean that if you already have React 17, it would keep using that, rather than also using React 16.

Any idea how to fix this on rjsf's end without having to changing the minimum React version supported to 17?

**Comment by dreadheadsic** [comment]
@epicfaace that works only for minor and patch version differences. For major versions you have to explicitly specify it in peerDependencies eg. `"react": "^16.x || ^17.x",`

**Comment by robertedjones** [comment]
I have forked the repo and changed the peer dependency to 17 but the issue is not fixed for me. However, adding bubbles: true as suggested by @dreadheadsic does seem to fix it.

**Comment by paintedbicycle** [comment]
I've created two CodePens, one with React 16 and one with React 17 in order to try to show the effect of this. React 17 is definitely causing submission issues. In my case it was for programatic form submission.

You can see the details and examples Pens here: https://github.com/rjsf-team/react-jsonschema-form/issues/2255

**Comment by timothyallan** [comment]
We still have to remember to manually change the rjsf package each time we re-install node_modules, or we cannot do programmatic form submissions.

**Comment by epicfaace** [comment]
Hmm, ok, so would setting the peer dependency to `"react": "^16.x || ^17.x",` fix this issue?

**Comment by paintedbicycle** [comment]
Just reading through this thread, it looks like conflicting reports on that.

Here is the documentation from React about possible issues related to the event propagation changes: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues

> For example, if you add manual DOM listeners with document.addEventListener(...), you might expect them to catch all React events. In React 16 and earlier, even if you call e.stopPropagation() in a React event handler, your custom document listeners would still receive them because the native event is already at the document level. With React 17, the propagation would stop (as requested!), so your document handlers would not fire:
```
> document.addEventListener('click', function() {
>   // This custom handler will no longer receive clicks
>   // from React components that called e.stopPropagation()
> });
```
> You can fix code like this by converting your listener to use the capture phase. To do this, you can pass { capture: true } as the third argument to document.addEventListener:
```
> document.addEventListener('click', function() {
>   // Now this event handler uses the capture phase,
>   // so it receives *all* click events below!
> }, { capture: true });
```

**Comment by dreadheadsic** [comment]
> Hmm, ok, so would setting the peer dependency to `"react": "^16.x || ^17.x",` fix this issue?

Yes, that will absolutely fix the issue.

**Comment by dreadheadsic** [comment]
> We still have to remember to manually change the rjsf package each time we re-install node_modules, or we cannot do programmatic form submissions.

@timothyallan offtopic, there's a great tool for that kind of situations so you don't have to change manually each time - https://github.com/ds300/patch-package

**Comment by timothyallan** [comment]
> > We still have to remember to manually change the rjsf package each time we re-install node_modules, or we cannot do programmatic form submissions.
> 
> @timothyallan offtopic, there's a great tool for that kind of situations so you don't have to change manually each time - https://github.com/ds300/patch-package

Thanks! We do have some docker scripts which do some automated bandaging of packages, but this seems a bit tidier!

**Comment by paintedbicycle** [comment]
Anything I can do to unstick this? What's holding us back?

**Comment by epicfaace** [comment]
Yeah, if you could make a PR that sets the peer dependency, and which also adds a test with React 17 in some way to ensure this doesn't regress, then that would be quick & easy to merge.

**Comment by dreadheadsic** [comment]
@epicfaace i'm curious, how would you proceed with writing test for this with current testing setup, cause to me it seems like there's no way. The closest thing that comes to my mind is setting up a bug reproduction repo and testing there.

**Comment by epicfaace** [comment]
Perhaps we could do something like this (https://medium.com/welldone-software/two-ways-to-run-tests-on-different-versions-of-the-same-library-f-e-react-17-react-16-afb7f861d1e9) to test with React 17 -- using npm aliases instead of yarn aliases, and running the "submit event should bubble" test on the core package.

**Comment by paintedbicycle** [comment]
I've got a PR for discussion [here](https://github.com/rjsf-team/react-jsonschema-form/pull/2312).

1. It updates the peer dependency
2. It suggests and approach for testing React 16 and React 17
3. It adds the ability to test the `Form_tests.js` file in both React 16 and React 17 by running `npm run test` and `npm run test-react-17`

Note: It needs discussion and cleanup before merge

**Comment by mucluck** [comment]
```
form.current.onSubmit({ 
    preventDefault: () => Function, 
    persist: () => Function 
})
```

Try this

**Comment by IanSavchenko** [comment]
It's a bit sad to see that this problem doesn't get resolved considering solution is a one-liner.

Here's a workaround that seems to work, if anyone is looking:
```ts
(formRef.current as any).formElement.dispatchEvent(
  new CustomEvent('submit', {
    cancelable: true,
    bubbles: true, // <-- actual fix
  }),
);
```

Please, let me know if you see any immediate issues with this.

**Comment by timothyallan** [comment]
> It's a bit sad to see that this problem doesn't get resolved considering solution is a one-liner.
> 
> Here's a workaround that seems to work, if anyone is looking:
> 
> ```ts
> (formRef.current as any).formElement.dispatchEvent(
>   new CustomEvent('submit', {
>     cancelable: true,
>     bubbles: true, // <-- actual fix
>   }),
> );
> ```
> 
> Please, let me know if you see any immediate issues with this.

That's what we've been patching manually for the past 6 months or so and it's been working fine.

**Comment by paintedbicycle** [comment]
We do have PRs for this, but we're trying to sort out an issue with setting up testing around that fix. Testing is proving harder than the fix. That's the TL;DR on what's going on. If you want to see more/help, here's the info:

I forked and created a branch that applied the above peerDependency fix. Then I added a test for programatic form submission using the example from the docs. @epicfaace pulled that PR into this repo in order to run the suite of tests set up in Github. You can see that here: https://github.com/rjsf-team/react-jsonschema-form/pull/2351

You can also see how he set up the new testing environment (both React 16 and React 17) here: https://github.com/rjsf-team/react-jsonschema-form/pull/2332#issuecomment-851128648

The issue is that the tests passed without the fix applied in both React 16 and 17. You can see that in the commit history - we reverted and re-applied the fix and let the tests run. They should have failed in React 17 without the fix and then worked once the fix was applied.

If we can sort out why that happened and then therefore be more confident about the testing and the fix, it should be easier to merge this fix.

If anyone wants to chat, we're also testing out a Discord server for rjsf here: https://discord.gg/SPXkvQrS

**Comment by epicfaace** [comment]
@IanSavchenko @timothyallan @paintedbicycle 

Basically, about this issue, I'm hesitant about merging a fix until we figure out:
- what exactly is the underlying issue?
- why would the fact that React 17 no longer attaches event handlers at the document level prevent you from submitting the form programmatically?
- what is the best fix that fixes the underlying issue -- `bubbles: true` or changing the peerDependency?
- how can we add a test that ensures this doesn't regress?

I'm sure this could be figured out with a couple hours of work / investigation, but it's not a priority for me to do all that work for free now ☹️ 

If someone is able to spend some time and get to the bottom of these questions, then we'd be in a much better place to merge it.

**Comment by dreadheadsic** [comment]
Yup, i Agree with @epicfaace 100%, it is still not clear enough what is causing this issue and what would the best solution be,
so i did some more testing/research and am more certain that changing the CustomEvent is correct fix.

Npm v7 now has a --legacy-peer-deps option for install which ignores older peer deps. So i ran that and went through node_modules to assert only React 17 is installed. After confirming i went and started the app, and the submit event wasn't being triggered!

Then i've found [this issue](https://github.com/facebook/react/issues/20151) which pretty much confirms that.
Especially [this comment](https://github.com/facebook/react/issues/20151#issuecomment-721015973) which suggests to use `form.requestSubmit` instead of letting the "submit" event bubble.

**Comment by epicfaace** [comment]
@dreadheadsic yep that makes sense. It looks like we added the following line with Event in https://github.com/rjsf-team/react-jsonschema-form/pull/1058:

```
this.formElement.dispatchEvent(new Event("submit"));
```

Then, we changed it to CustomEvent in https://github.com/rjsf-team/react-jsonschema-form/pull/1432:

```
this.formElement.dispatchEvent(new CustomEvent("submit", { cancelable: true }));
```

I'm not sure why we called dispatchEvent on a new Event object in #1058. It seems like the solution here would be just to call `form.requestSubmit` instead?

If we agree (and check) that `form.requestSubmit()` is the right fix, I think this satisfies my first three questions, honestly, because creating a CustomEvent seems to be a hacky solution anyway, and `form.requestSubmit()` seems better.

We should figure out the final question though -- how can we add a test that ensures this doesn't regress?

**Comment by josh08h** [comment]
@paintedbicycle Do you know if this issue is still being worked on? Would love to get the fix in for this one.

**Comment by paintedbicycle** [comment]
I've lost track of the status of it. There arweree several approaches to fixes in different PRs, but I don't remember if there was ever one PR with both the fix and passing tests on React 16 and 17 in the same environment

**Comment by kfcaio** [comment]
Is it fixed?

**Comment by epicfaace** [comment]
Not yet.

> if there was ever one PR with both the fix and passing tests on React 16 and 17 in one spot

This is exactly what we need!
