### ISSUE TITLE
separate view schema to display the form data

### ISSUE THREAD

**Issue by arunkumar413** [rjsf-team/react-jsonschema-form#2308]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
Can we have a feature (Schema) to just view the form data? Currently the schema allows for form editor but not for viewing the form data. It would be great if there is a schema for just viewing/displaying the submitted/fetched form data so that we'll have total of three  schemas that allows us to switch between edit form data and view form data. 

1) Form schema for form editor (what inputs should the form contain)
2) UI schema for displaying form editor (how the form editor controls and inputs should display)
3) View Schema (for just displaying the form submitted/fetched data) 

[separate view schema for forms]

A separate view shema just for displaying the form data

#### Expected behavior

[What you expected to happen]
A seperate view shcema just for displaying the form data  that allows to toggle between edit form and view form data

#### Actual behavior

[What actually happened]

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by arunkumar413** [comment]
With form schema and view schema it would make it easier to toogle between edit and view form data.

**Comment by ronnyek** [comment]
I was actually going to just submit an issue for this very thing. rjsf is already a very powerful framework for entering and even displaying data in a form type scope... but wondering if the same schema/ui-schema/data values, and actually just render as a sort of "details" view.

Even if this is a separate component that just happened to take some of the same properties (data, schema) and use some of the same uischema to lay out the details. I feel like this functionality could be pretty huge. Would this be something that would potentially be accepted as a PR?

**Comment by epicfaace** [comment]
I think that if this feature were to be implemented, it may best be implemented as part of a specific theme; perhaps specific widgets / fields could be added for each theme that represent the "view-only" part of a form.

**Comment by adjenks** [comment]
I found myself here because I was hoping that readOnly would make the data appear without any input element whatsoever and just display the data. I could imagine this being applied to a particular field or globally.

In my application, I first generate a data structure of known data that cannot be changed and it is guaranteed to validate against the schema, all of these fields are set to readOnly, the rest of the schema is left for the user to fill out. However, I was disappointed that the readOnly fields look like they were meant to be edited at some point and that they are slightly grey which makes them a bit difficult to read in most UI configurations without adding custom CSS.

So, please create some for of uiSchema property called "ui:displayOnly", or make make the JSON-Schema readOnly behaviour default to just display the data without any input elements.

My solution will be to create my own widget and set every display item to that widget, which is very simple to implement, but I still think it should be a built-in with each UI library.

**Comment by adjenks** [comment]
Hello stale bot, I still think this is a good idea.
