### ISSUE TITLE
NONE of the codepen examples/snippets in the documentation work.

### ISSUE THREAD

**Issue by M-S-Saurabh** [rjsf-team/react-jsonschema-form#2447]
### Prerequisites

- [ ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

The documentation is inaccessible because none of the examples shown work. The snippets for all examples do not compile and results are blank.

### Steps to Reproduce

1. Go to https://react-jsonschema-form.readthedocs.io/en/latest/quickstart/
2. See Codepen widgets 
3. Result section of these widgets are all blank

#### Expected behavior

The examples in documentation should work and show the generated form on the right side of the Codepen widgets.

#### Actual behavior

Codepen widgets do not compile properly, right side (result) is blank or displays an error message saying "Not found".
Makes me want to pull my hair out cuz I cannot understand how to use your library.

### Version

You can usually get this information in your `package.json` or in the file URL if you're using the unpkg one.

**Comment by epicfaace** [comment]
It seems like v3 broke the docs codepens; going to revert it to 2.5.1 for now using https://github.com/rjsf-team/react-jsonschema-form/pull/2448.

**Comment by epicfaace** [comment]
Perhaps https://github.com/rjsf-team/react-jsonschema-form/pull/2211 caused this issue? What do you think @wegry ?

**Comment by wegry** [comment]
I’m not familiar with the codepen examples, but I’d expect that polyfills
would need to be loaded for older browsers as part of the codepen at the
very least.

@M-S-Saurabh what browser are you trying this in?

@epicface I can take a look sometime later this week, probably.

On July 13, 2021 at 12:32:56, Ashwin Ramaswami ***@***.***)
wrote:

Perhaps #2211 <https://github.com/rjsf-team/react-jsonschema-form/pull/2211>
caused this issue? What do you think @wegry <https://github.com/wegry> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rjsf-team/react-jsonschema-form/issues/2447#issuecomment-879233458>,
or unsubscribe
