### ISSUE TITLE
Playground is not up to date with latest version

### ISSUE THREAD

**Issue by ssbyoung** [rjsf-team/react-jsonschema-form#2450]
### Description

https://rjsf-team.github.io/react-jsonschema-form/ is not a good place to reference as it does not have more recent bugs such as https://github.com/rjsf-team/react-jsonschema-form/issues/2449

**Comment by epicfaace** [comment]
The playground does build from master; the latest build was today morning from master (https://github.com/rjsf-team/react-jsonschema-form/runs/2944555353?check_suite_focus=true). I don't think this is because the playground isn't up to date with the latest version; perhaps #2449 cannot be reproduced in the playground as it only shows up in particular other environments?
