### ISSUE TITLE
FormData doesn't recognize null as a value

### ISSUE THREAD

**Issue by michalchar** [rjsf-team/react-jsonschema-form#2469]
### Description
There is no support for using a Form component as a single field with a schema of type null.
Because of the formData property doesn't recognize null as a value.
[Example](https://jsfiddle.net/michalc/b5yt4zrj/4/)
I saw this happen because of this [code](https://github.com/rjsf-team/react-jsonschema-form/blob/dec3ef4284505a2c29ac5c7b6c4bd8a5f9ed505f/packages/core/src/utils.js#L325)
(The null value was not excluded by the condition as the other falsy values, therefore it is overridden by the default).

### Steps to Reproduce

1. Schema of type null
2. FormData is null

#### Expected behavior

The Form recognizes null as a valid value.

#### Actual behavior

An error occurs that the value is invalid.

### Version

3.0.0

**Comment by doron-au10tix** [comment]
Hi, is this planned to be fixed?

**Comment by wshart** [comment]
For anyone else, the simplest solution for me was to
1. check if the `schema` is a single null field
2. If yes, then set `noValidate` to `true`

**Comment by heath-freenome** [comment]
@wshart @michalchar There is a good chance that this issue was fixed in the 5.x release by visual inspection of the [old code](https://github.com/rjsf-team/react-jsonschema-form/blob/dec3ef4284505a2c29ac5c7b6c4bd8a5f9ed505f/packages/core/src/utils.js#L325) indicated above and the newly refactored and upgraded [code](https://github.com/rjsf-team/react-jsonschema-form/blob/bf9424db355ff07308f51eeec6198ac6f59ef4ba/packages/utils/src/schema/getDefaultFormState.ts#L380) that exists today.
