### ISSUE TITLE
Invalid validation logic for nested "dependencies" with "additionalProperties" set to false

### ISSUE THREAD

**Issue by asalmoqbel** [rjsf-team/react-jsonschema-form#2484]
### Prerequisites

- [√] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [√] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [√] Ideally, I'm providing a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcmVZb3VNYXJyaWVkIjoiTm8ifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7ImFyZVlvdU1hcnJpZWQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvWWVzTm8iLCJ0aXRsZSI6IkFyZSB5b3UgbWFycmllZD8iLCJkZWZhdWx0IjoiTm8ifX0sImRlcGVuZGVuY2llcyI6eyJhcmVZb3VNYXJyaWVkIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImFyZVlvdU1hcnJpZWQiOnsiZW51bSI6WyJObyJdfX19LHsicHJvcGVydGllcyI6eyJhcmVZb3VNYXJyaWVkIjp7ImVudW0iOlsiWWVzIl19LCJmYW1pbHlEZXRhaWxzIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkZhbWlseSBEZXRhaWxzIiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7ImRvWW91SGF2ZUNoaWxkcmVuIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1llc05vIiwidGl0bGUiOiJEbyB5b3UgaGF2ZSBjaGlsZHJlbj8iLCJkZWZhdWx0IjoiTm8ifX0sImRlcGVuZGVuY2llcyI6eyJkb1lvdUhhdmVDaGlsZHJlbiI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJkb1lvdUhhdmVDaGlsZHJlbiI6eyJlbnVtIjpbIk5vIl19fX0seyJwcm9wZXJ0aWVzIjp7ImRvWW91SGF2ZUNoaWxkcmVuIjp7ImVudW0iOlsiWWVzIl19LCJudW1iZXJPZkNoaWxkcmVuIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJOdW1iZXIgb2YgQ2hpbGRyZW4ifX19XX19fX19XX19LCJkZWZpbml0aW9ucyI6eyJZZXNObyI6eyJlbnVtIjpbIlllcyIsIk5vIl19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=) demonstrating the issue.

### Description

It looks like the implemented logic for validating `"additionalProperties": false` with **nested** `dependencies` is not correct, it consider the conditional new field in the dependencies as additional properties and raise a validation error.

This doesn't happen with the first level dependencies, but when there are dependencies inside dependencies this issue is happen.

### Steps to Reproduce

1. Open the [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhcmVZb3VNYXJyaWVkIjoiTm8ifSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7ImFyZVlvdU1hcnJpZWQiOnsiJHJlZiI6IiMvZGVmaW5pdGlvbnMvWWVzTm8iLCJ0aXRsZSI6IkFyZSB5b3UgbWFycmllZD8iLCJkZWZhdWx0IjoiTm8ifX0sImRlcGVuZGVuY2llcyI6eyJhcmVZb3VNYXJyaWVkIjp7Im9uZU9mIjpbeyJwcm9wZXJ0aWVzIjp7ImFyZVlvdU1hcnJpZWQiOnsiZW51bSI6WyJObyJdfX19LHsicHJvcGVydGllcyI6eyJhcmVZb3VNYXJyaWVkIjp7ImVudW0iOlsiWWVzIl19LCJmYW1pbHlEZXRhaWxzIjp7InR5cGUiOiJvYmplY3QiLCJ0aXRsZSI6IkZhbWlseSBEZXRhaWxzIiwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJwcm9wZXJ0aWVzIjp7ImRvWW91SGF2ZUNoaWxkcmVuIjp7IiRyZWYiOiIjL2RlZmluaXRpb25zL1llc05vIiwidGl0bGUiOiJEbyB5b3UgaGF2ZSBjaGlsZHJlbj8iLCJkZWZhdWx0IjoiTm8ifX0sImRlcGVuZGVuY2llcyI6eyJkb1lvdUhhdmVDaGlsZHJlbiI6eyJvbmVPZiI6W3sicHJvcGVydGllcyI6eyJkb1lvdUhhdmVDaGlsZHJlbiI6eyJlbnVtIjpbIk5vIl19fX0seyJwcm9wZXJ0aWVzIjp7ImRvWW91SGF2ZUNoaWxkcmVuIjp7ImVudW0iOlsiWWVzIl19LCJudW1iZXJPZkNoaWxkcmVuIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJOdW1iZXIgb2YgQ2hpbGRyZW4ifX19XX19fX19XX19LCJkZWZpbml0aW9ucyI6eyJZZXNObyI6eyJlbnVtIjpbIlllcyIsIk5vIl19fX0sInVpU2NoZW1hIjp7fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOnRydWUsImxpdmVPbWl0Ijp0cnVlfX0=) which contains the example
2. Answer the first question ( Are you married? ) with ( Yes ) to open the dependent fields
3. Answer the second question ( Do you have children? ) with ( Yes ) to open the "nested" dependent fields
4. Type any number in ( Number of Children ), 1 for example
5. Submit
6. You will got the error ( `.familyDetails['numberOfChildren'] is an invalid additional property` )
7. Also, try to change the answer for ( Do you have children? ) to ( No ), the data `"numberOfChildren": 1` is still there and the feature ( Omit extra data ) didn't work

#### Expected behavior

1. No errors should appear as this is valid schema
2. ( Omit extra data ) should work

#### Actual behavior

1. I got error ( `.familyDetails['numberOfChildren'] is an invalid additional property` )
2. The feature ( Omit extra data ) works with ( Are you married? ) but doesn't work when change the answer for ( Do you have children? ) to ( No ), the data `numberOfChildren` is still there

### Version
I have tried with 2 versions + the playground:
- 3.0.0
- 2.4.2

**Comment by angelsvirkov** [comment]
I also encountered a similar error, which I believe might be related. Below you can find an example of that error.

I dug into the code of rjsf and I think I found the root cause for the problem. I think what happens is the following.
1. RJSF stores the initial formData state
2. A user changes an option in a UI element which is the result of `oneOf, anyOf, ...`
3. The user adds the corresponding fields for the subSchema of the selected option and clicks `Submit`
4. During the `validateFormData()` execution RJSF tries to get the defaultFormState from the initial data.
5. On line https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/validate.js#L178 the `getDefaultFormState()` function is invoked with a 4th parameter `true`, which makes the function include undefined keys from the initial state.
6. The resulting formData after invoking the function on step 5 contains both the user-added properties from step 2. plus the properties from the initial form data equal to undefined. 
7. Thus, ajv fails the validation, because it receives data that neither fits any of the subSchema, because RJSF manipulated the formData by including extra fields which are shown in the UI

A friendly git blame showed that @epicfaace added this option with the comment below in attempt to solve some other bug I guess. Nevertheless, I think the current RJSF cannot work with subSchemas and additional properties due to that. I guess a fix for that would be very easy if @epicfaace by any chance remembers the reason for adding this additional `includeUndefinedValues` option. Could we maybe remove it?

> // Include form data with undefined values, which is required for validation.

---

Second example of the current problem in the issue
- [Playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJzd2l0Y2hPcHRpb24iOnsiYiI6InV5dWkifX0sInNjaGVtYSI6eyJ0aXRsZSI6IkJ1ZyIsImRlc2NyaXB0aW9uIjoiRXhhbXBsZSBvZiBidWcgaHR0cHM6Ly9naXRodWIuY29tL3Jqc2YtdGVhbS9yZWFjdC1qc29uc2NoZW1hLWZvcm0vaXNzdWVzLzI0ODQgLiBPcHRpb24gQiB2YWxpZGF0aW9uIGluY29ycmVjdGx5IGZhaWxzLiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InN3aXRjaE9wdGlvbiI6eyJ0aXRsZSI6Ik9wdGlvbiBTd2l0Y2giLCJhbnlPZiI6W3sidGl0bGUiOiJPcHRpb24gQSIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImEiOnsidGl0bGUiOiJQcm9wZXJ0eSBBIiwidHlwZSI6Im51bWJlciJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJyZXF1aXJlZCI6WyJhIl19LHsidGl0bGUiOiJPcHRpb24gQiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImIiOnsidGl0bGUiOiJQcm9wZXJ0eSBiIiwidHlwZSI6InN0cmluZyJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJyZXF1aXJlZCI6WyJiIl19XX19LCJhZGRpdGlvbmFsUHJvcGVydGllcyI6ZmFsc2UsInJlcXVpcmVkIjpbInN3aXRjaE9wdGlvbiJdLCIkc2NoZW1hIjoiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIn0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSJ9LCJsYXN0TmFtZSI6eyJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6Im1hdGVyaWFsLXVpIiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjp0cnVlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)
- To reproduce simply switch between Option A and Option B and try to validate them

**Comment by epicfaace** [comment]
FYI here's the commit mentioned in the git blame: https://github.com/rjsf-team/react-jsonschema-form/commit/6728977b0085ef37c310b4d40d076a2622664ba7#diff-83b6fb1796485bd8fd2abf97de6328dc2234ca3b2f7c00c5e7e27d0a1b0acd1fR177


> Could we maybe remove it?

I don't remember what it's for. Can you try removing it and see if the tests still pass?

**Comment by angelsvirkov** [comment]
> I don't remember what it's for. Can you try removing it and see if the tests still pass?

I tried removing it and 3 tests failed. These are

1. https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/test/SchemaField_test.js#L381
```
  1) SchemaField
       errors
         should render its own errors:
     TypeError: Cannot read property 'addError' of undefined
      at validate (test/SchemaField_test.js:463:18)
      at validateFormData (src/validate.js:268:24)
```

2. https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/test/SchemaField_test.js#L396
```
  2) SchemaField
       errors
         should pass errors to child component:
     TypeError: Cannot read property 'addError' of undefined
      at validate (test/SchemaField_test.js:463:18)
      at validateFormData (src/validate.js:268:24)
```
3) https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/test/SchemaField_test.js#L416
```
  3) SchemaField
       errors
         Custom error rendering
           should pass rawErrors down to custom widgets:
     TypeError: Cannot read property 'addError' of undefined
      at validate (test/SchemaField_test.js:463:18)
      at validateFormData (src/validate.js:268:24)
 ```
 
 I guess, there is some logic in the way the schema is validated and this validation indeed relies on existing keys as stated by the comment in the code. Nevertheless, the same schema and data passes the validation in a standalone ajv test I executed. I am not quite sure if there is a way to improve the behaviour of the validation to not rely on keys being there with `{ someKey: undefined}`.
