### ISSUE TITLE
Bug: Custom field that is anyOf displays twice

### ISSUE THREAD

**Issue by abemedia** [rjsf-team/react-jsonschema-form#2691]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using a custom field that's an `anyOf`, the field is displayed twice. First on it's own and then again wrapped in the `AnyOfField`.
Looking at the code at https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/fields/SchemaField.js#L356-L381 I can see the field is first used and then the `AnyOf` and `OneOf` fields are used below. Might be an idea to wrap the latter in an if statement so if it's a custom field it doesn't show (that's what I did in a local override).

### Steps to Reproduce

See fiddle: https://jsfiddle.net/pajetb10/

#### Expected behavior

AnyOfField isn't used as we have supplied a custom field.

#### Actual behavior

The field is displayed twice. First on it's own and then again wrapped in the `AnyOfField`.

### Version

3.2.1

**Comment by romainbessugesmeusy** [comment]
Hello there,
I'm encountering the issue as well. Here's a Code sandbox explaining my situation:
 https://codesandbox.io/s/hopeful-dust-vs82wn?file=/src/Playground.js

**Comment by truh** [comment]
Was about to report the same problem.

### Current behavior

The customized field is rendered as
* Custom field
* Select box
* Custom field (again but a bit more nested)

### Expected behavior

I thought it would only render the custom field in place of the default view of the relevant part of the form.

I expected to be able to handle the anyOf choice within my custom field.

### Steps To Reproduce

https://codepen.io/jakob-moonvision/pen/NWyRXxv (this is a minimal example hence a rather pointless use of anyOf but I have the same problem with a more complex )

* Create a schema with a anyOf
* Create custom field
* Create a uiSchema where the custom field is set for the schema containing the anyOf

### Environment

- OS: macOS Monterey 12.3.1
- Node: 14.17.4
- yarn: 1.22.17

**Comment by truh** [comment]
I believe that I have found a solution to this problem. Will open a PR when I can get the development environment working.

In the meanwhile you can try to pass this https://gist.github.com/truh/ce6a1b93bdd0b7533d2d65f5c5290300 for the SchemaField.
