### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by bwied** [rjsf-team/react-jsonschema-form#3440]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

core

### What is your question?

It seems like validation on the "Live Playground" is no longer working.  Could you confirm whether or not you are experiencing the same thing?

**Comment by bwied** [comment]
It seems as though required field validation is the part that is not working.  I apologize if this is something that changed with v5 that is covered in the documentation.

**Comment by nickgros** [comment]
@bwied which playground examples aren't behaving as expected? To fix #675 and #3424, we've changed how we instantiate formData, which could have broken validation for some of the examples. We'd probably want to fix the examples themselves.

**Comment by bwied** [comment]
@nickgros I was using the simple example and deleting either first name or last name and then clicking submit. It looks like #3424 already covers this issue though, so I'm sorry about that.  

The other issue I was seeing is/was related to html5validation and the first invalid input control being out of view when clicking the submit button. This [stackoverflow ](https://stackoverflow.com/questions/54470841/html5-form-validation-out-of-view-not-getting-message-popup-mac-safari) post seems to describe this behavior as more of a browser implementation feature/bug in which the act of scrolling immediately hides the displayed validation popup.  I was seeing the same behavior in both Chrome and Edge.

**Comment by tyrdavis** [comment]
Seconding this. We're trying to migrate to v5 and required fields never produce validation errors. On the simple example in the playground, you can submit the form without either of the first name or last name fields filled, and neither will ever show an error.

**Comment by heath-freenome** [comment]
The reason the simple example validates is because there is an empty string being provided to the `formData` via the `ui:emptyValue` prop in the `uiSchema` so there will always be a valid string. If you remove the `ui:emptyValue` for say, `lastName` as shown in this [modified simple example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImFnZSI6NzUsImJpbyI6IlJvdW5kaG91c2Uga2lja2luZyBhc3NlcyBzaW5jZSAxOTQwIiwicGFzc3dvcmQiOiJub25lZWQiLCJ0ZWxlcGhvbmUiOiIxLTgwMC1LSUNLQVNTIn0sInNjaGVtYSI6eyJ0aXRsZSI6IkEgcmVnaXN0cmF0aW9uIGZvcm0iLCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIGZvcm0gZXhhbXBsZS4iLCJ0eXBlIjoib2JqZWN0IiwicmVxdWlyZWQiOlsiZmlyc3ROYW1lIiwibGFzdE5hbWUiXSwicHJvcGVydGllcyI6eyJmaXJzdE5hbWUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiRmlyc3QgbmFtZSIsImRlZmF1bHQiOiJDaHVjayJ9LCJsYXN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJMYXN0IG5hbWUifSwiYWdlIjp7InR5cGUiOiJpbnRlZ2VyIiwidGl0bGUiOiJBZ2UifSwiYmlvIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IkJpbyJ9LCJwYXNzd29yZCI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJQYXNzd29yZCIsIm1pbkxlbmd0aCI6M30sInRlbGVwaG9uZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJUZWxlcGhvbmUiLCJtaW5MZW5ndGgiOjEwfX19LCJ1aVNjaGVtYSI6eyJmaXJzdE5hbWUiOnsidWk6YXV0b2ZvY3VzIjp0cnVlLCJ1aTplbXB0eVZhbHVlIjoiIiwidWk6YXV0b2NvbXBsZXRlIjoiZmFtaWx5LW5hbWUifSwibGFzdE5hbWUiOnsidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGggeWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZX19), you will see the required field validation occurs. Are you using the `ui:emptyValue` behavior?

**Comment by heath-freenome** [comment]
I am updating the simple example to at least make `lastName` fail the required field validation when nothing is provided.

**Comment by heath-freenome** [comment]
> @nickgros I was using the simple example and deleting either first name or last name and then clicking submit. It looks like #3424 already covers this issue though, so I'm sorry about that.
> 
> The other issue I was seeing is/was related to html5validation and the first invalid input control being out of view when clicking the submit button. This [stackoverflow ](https://stackoverflow.com/questions/54470841/html5-form-validation-out-of-view-not-getting-message-popup-mac-safari) post seems to describe this behavior as more of a browser implementation feature/bug in which the act of scrolling immediately hides the displayed validation popup. I was seeing the same behavior in both Chrome and Edge.

There is a new feature in 5.1.0 that allows you to select whether the form automatically focuses on the first field with a validation error. Maybe this will help you?

**Comment by bwied** [comment]
@heath-freenome I'm sorry that I overlooked the ui:emptyValue prop, but thank you for updating the sample anyways.  

To answer your question, the focusOnFirstError prop did indeed help.  I appreciate your follow-up and the continued effort that you and everybody else are putting into this project.
