### ISSUE TITLE
simplest way to add a custom TextInput 

### ISSUE THREAD

**Issue by dagda1** [rjsf-team/react-jsonschema-form#3481]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)

### What theme are you using?

material-ui

### What is your question?

I want to set these properties in a material-ui `TextField`

```ts
<TextField
  id={param.key}
  helperText={schema.title}
  variant="outlined"
```

After reading the docs, the only way I can see of doing this is to add a `TextWidget` to the `widgets` prop of the `material-ui` form.

Currently the `TextWidget` is the `BaseInputTemplate` and that is a lot of code to replace and also then I have to keep my `BaseInputTemplate` up to date with the one in this repo.

Is there a simpler way, maybe using `WrapIfAdditionalTemplate` but I'm not entirely sure how to use that.

**Comment by heath-freenome** [comment]
@dagda1 You can create a custom widget that uses `BaseInputTemplate` and passes the additional props along. If you look at the implementation of [TextareaWidget](https://github.com/rjsf-team/react-jsonschema-form/blob/df4e0f70b3eb4661a82389974c6d10f4e0f597c4/packages/material-ui/src/TextareaWidget/TextareaWidget.tsx#L30) for `@rjsf/material-ui` you can see how to do it. Instead of `multiline` and `rows` pass your prop. Then, using the `uiSchema` you can assign this widget to the field you need it on. If you want to make ALL textfields do this, then you can import the `BaseInputTemplate` from the `@rjsf/material-ui` directly from the exported `Templates` container and wrap it with your own custom version that passes the props through. Something like:
```
import { BaseInputTemplateProps } from '@rjsf/utils';
import { Templates } from '@rjsf/material-ui';

export default MyBaseInputTemplate(props: BaseInputTemplateProps) {
   const { schema } = props;
   const { BaseInputTemplate } = Templates;
   // get your param prop from where you need to
   return <BaseInputTemplate {...props} id={param.key} helperText={schema.title} variant="outlined" />;
}
```

Then pass `MyBaseInputTemplate` into the `templates` prop on `Form`

**Comment by dagda1** [comment]
@heath-freenome thank you for the detailed answer.  Much appreciated!

**Comment by heath-freenome** [comment]
@dagda1 Note that `BaseInputTemplateProps` is a new type that is part of the 5.2.1 release, coming out at any moment, keep your eye out for it
