### ISSUE TITLE
how do I submit the form inside a custom filed component

### ISSUE THREAD

**Issue by Easy-Ez** [rjsf-team/react-jsonschema-form#3681]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I'm now showing a list of options by way of a custom field.

I want to hide the submit button and submit the form when the option is clicked.

By reading the documentation, I can hide the submit button by configuring submitButtonOptions norender to true.

But how do I submit the form when the option is clicked, or how do I submit the form inside a custom filed component?

**Comment by Easy-Ez** [comment]
```ts
const formRef = createRef<Form>();
  

 <ThemeForm
          ref={formRef}
          formContext={{
            form: formRef,
          }}
/>

// custom field

const CustomField = <T = any,
    S extends StrictRJSFSchema = RJSFSchema,
    F extends FormContextType = any>(props: FieldProps<T, S, F>) => {
    return <div>
        <button onClick={()=>{
            props.formContext?.form?.current?.submit();
        }}>inside sumbit</button>
    </div>;
};

```
I found a way to store the formRef in the formContext and then fetch it from the formContext in the custom field component.
I don't know if this is a best practice.

**Comment by nickgros** [comment]
@Easy-Ez this is how we recommend doing [programmatic submission](https://rjsf-team.github.io/react-jsonschema-form/docs/advanced-customization/internals/#submit-form-programmatically) and formContext is generally useful for passing along data like this ref, so your example seems like the best way to do it.

I'm closing this since you answered your own question, but please feel free to open a new issue and let us know if this doesn't work for you.
