### ISSUE TITLE
Required field is removed from formData if edited and then left blank

### ISSUE THREAD

**Issue by MatinF** [rjsf-team/react-jsonschema-form#3728]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

I have a Rule Schema with a required string field, with a default value of `""`, i.e. a blank string.

When I load the Rule Schema and submit with `noHtml5Validate={true}`, it works as intended - i.e. the formData contains the field `my_string_field` with a value of `""` as intended and I can submit the form. However, if I modify the field in any way and then again set it to an empty string, the field `my_string_field` is removed from the formData entirely - resulting in a validation error.

Below is my schema example, which can be loaded in the playground for replication:

[PLAYGROUND LINK](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0X29iamVjdCI6eyJteV9zdHJpbmdfZmllbGQiOiIifX0sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7InRlc3Rfb2JqZWN0Ijp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im15X3N0cmluZ19maWVsZCI6eyJ0aXRsZSI6Im15X3N0cmluZ19maWVsZCIsInR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiIiwicGF0dGVybiI6Il4ofFswLTldezQsOH0pJCJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJyZXF1aXJlZCI6WyJteV9zdHJpbmdfZmllbGQiXX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOnBsYWNlaG9sZGVyIjoidWk6ZW1wdHlWYWx1ZSBjYXVzZXMgdGhpcyBmaWVsZCB0byBhbHdheXMgYmUgdmFsaWQgZGVzcGl0ZSBiZWluZyByZXF1aXJlZCIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIiwidWk6ZW5hYmxlTWFya2Rvd25JbkRlc2NyaXB0aW9uIjp0cnVlLCJ1aTpkZXNjcmlwdGlvbiI6Ik1ha2UgdGV4dCAqKmJvbGQqKiBvciAqaXRhbGljKi4gVGFrZSBhIGxvb2sgYXQgb3RoZXIgb3B0aW9ucyBbaGVyZV0oaHR0cHM6Ly9wcm9iYWJseXVwLmNvbS9tYXJrZG93bi10by1qc3gvKS4ifSwibGFzdE5hbWUiOnsidWk6YXV0b2NvbXBsZXRlIjoiZ2l2ZW4tbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRoaW5ncyAqKmJvbGQqKiBvciAqaXRhbGljKi4gRW1iZWQgc25pcHBldHMgb2YgYGNvZGVgLiA8c21hbGw+QW5kIHRoaXMgaXMgYSBzbWFsbCB0ZXh0cy48L3NtYWxsPiAifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fSwidGhlbWUiOiJkZWZhdWx0IiwibGl2ZVNldHRpbmdzIjp7InNob3dFcnJvckxpc3QiOiJ0b3AiLCJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwibm9IdG1sNVZhbGlkYXRlIjp0cnVlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiZW1wdHlPYmplY3RGaWVsZHMiOiJwb3B1bGF0ZUFsbERlZmF1bHRzIn19fQ==)

```
{
  "properties": {
    "test_object": {
      "type": "object",
      "properties": {
        "my_string_field": {
          "title": "my_string_field",
          "type": "string",
          "default": "",
          "pattern": "^(|[0-9]{4,8})$"
        }
      },
      "additionalProperties": false,
      "required": [
        "my_string_field"
      ]
    }
  }
}
```

### Expected Behavior

The expected behavior would be that the field, `my_string_field`, is kept in the formData as an empty string if the user modifies the field and then sets it to blank again - i.e. the field should not be automatically removed from the formData in this case. At least I believe this is how it must be supposed to work with `noHtml5Validate={true}`

### Steps To Reproduce

Open playground link and hit submit to verify that the form can be submitted with the default values. 

Then modify the field and again make it blank, then try to resubmit. Notice how the formData now excludes the field object.

### Environment

```markdown
latest version (playground)
```

**Comment by nickgros** [comment]
@MatinF You can use the uiSchema option ui:emptyValue to ensure the empty case falls back to the empty string instead of removing it from the formData.

There's a small bit of info about it in the docs [here](https://rjsf-team.github.io/react-jsonschema-form/docs/usage/validation/#the-case-of-empty-strings). And here's a [playground example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0X29iamVjdCI6eyJteV9zdHJpbmdfZmllbGQiOiIifX0sInNjaGVtYSI6eyJwcm9wZXJ0aWVzIjp7InRlc3Rfb2JqZWN0Ijp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im15X3N0cmluZ19maWVsZCI6eyJ0aXRsZSI6Im15X3N0cmluZ19maWVsZCIsInR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiIiwicGF0dGVybiI6Il4ofFswLTldezQsOH0pJCJ9fSwiYWRkaXRpb25hbFByb3BlcnRpZXMiOmZhbHNlLCJyZXF1aXJlZCI6WyJteV9zdHJpbmdfZmllbGQiXX19fSwidWlTY2hlbWEiOnsidGVzdF9vYmplY3QiOnsibXlfc3RyaW5nX2ZpZWxkIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTpwbGFjZWhvbGRlciI6InVpOmVtcHR5VmFsdWUgY2F1c2VzIHRoaXMgZmllbGQgdG8gYWx3YXlzIGJlIHZhbGlkIGRlc3BpdGUgYmVpbmcgcmVxdWlyZWQifX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOnRydWUsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6ZmFsc2UsImxpdmVPbWl0IjpmYWxzZSwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjoicG9wdWxhdGUiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19).
