### ISSUE TITLE
How to implement `ajv-keywords` with rjsf `@rjsf/validator-ajvX`?

### ISSUE THREAD

**Issue by michal-kurz** [rjsf-team/react-jsonschema-form#3972]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I want to use the [uniqItemProperties](https://ajv.js.org/packages/ajv-keywords.html#uniqueitemproperties) keyword from `ajv-keyword` library - how can I make this work with `@rjsf/validator-ajvX`?

I am using ajv-6 validator invoked like this: 

``` typescript
import { customizeValidator } from '@rjsf/validator-ajv6'
const validator = customizeValidator({ customFormats: CUSTOM_FORMAT_CRITERIA as any })
```

The custom keyword should be applied to the `ajv` instance itself like so:
``` typescript
require('ajv-keywords')(ajv, ['uniqueItemProperties'])
```
`ajv-keyword` then calls `ajv.addKeyword()` on the `ajv` instance - is there a clean way of applying it with `@rjsf/validator-ajv6`?

**Comment by heath-freenome** [comment]
@michal-kurz at the moment we don't expose the internal `ajv` instance anywhere as we are trying to make validators implementation agnostic. That said, it probably makes sense for us to update our `customizeValidator()` to expose the underlying `ajv` instance so that you can do what you need. I'll push a PR with the changes soon

**Comment by michal-kurz** [comment]
Thank you, @heath-freenome !
