### ISSUE TITLE
Adding different display name to enum with ui-Schema

### ISSUE THREAD

**Issue by perelin** [rjsf-team/react-jsonschema-form#4215]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

We are auto-generating our base json-schema files directly from a (graphql) API schema. So enums there are not meant for human consumption and need labels. 

We use ui-Schema to augment the generated json-schema files with all necessary presentation layer things (titles, order, etc). The only thing that we dont manage to do is give enums new labels. 

How can we approach this?

**Comment by nickgros** [comment]
I don't think you can do that today, the only ways to label an enum are using `oneOf`/`title` or the deprecated & nonstandard `enumNames` property in the JSON Schema ([docs](https://rjsf-team.github.io/react-jsonschema-form/docs/json-schema/single/#custom-labels-for-enum-fields)).

The reason we deprecated `enumNames` is because it's a nonstandard JSON Schema field. I think it could be useful to have a similar feature added to the `uiSchema`. We'd be happy to review a PR if you are interested in contributing this feature!

**Comment by perelin** [comment]
Late reply, sorry.

I found that it does seem possible somehow to attach a title to a any/oneOf somehow. But there are other issues keeping me :) https://github.com/rjsf-team/react-jsonschema-form/issues/4260 thanks anyway!

**Comment by nickgros** [comment]
Glad you have a workaround for this issue @perelin . If you don't mind, I want to re-open this ticket because I think we'll want to keep `enumNames` in the library until we provide some way to override `enum` display values via the uiSchema.

**Comment by heath-freenome** [comment]
Fixed with https://github.com/rjsf-team/react-jsonschema-form/pull/4263
