### ISSUE TITLE
How to get `rawErrors` for parent schema or `errorSchema` in custom BaseInputTemplate

### ISSUE THREAD

**Issue by alfonsoar** [rjsf-team/react-jsonschema-form#4271]
### Prerequisites

- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)

### What theme are you using?

core

### What is your question?

I am specifying a custom `BaseInputTemplate` and `ObjectFieldTemplate` in my project. My schema is complex enough that I have a nested properties inside of a `allOf/if/then` schema. See example: https://stackblitz.com/edit/vitejs-vite-srg8et?file=src%2FApp.tsx

In the example above, when you submit without entering any information you will see validation failed. But the inputs will not be in an error state since we do not have anything in the `rawErrors` prop being passed to the `BaseInputTemplate`. 

How do I get the `rawErrors` from the parent schema (in this case it would be `usernameAndPassword`) in this field? Alternatively is it possible to pass the full `errorSchema` to the `BaseInputTemplate` instead? 

**note:** I understand I can get the `errorSchema` from `ErrorListTemplate` but this means I would need to pass it down via context which I don't think is ideal. 

If you switch the auth type to "SSO" and submit without entering information you will observe the input in a error state.

**Comment by nickgros** [comment]
If you look at the raw Ajv errors [in the playground](http://localhost:8080/#eyJmb3JtRGF0YSI6eyJhdXRoZW50aWNhdGlvbiI6eyJjcmVkZW50aWFsVHlwZSI6InVzZXJuYW1lIn19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbImF1dGhlbnRpY2F0aW9uIl0sInByb3BlcnRpZXMiOnsiYXV0aGVudGljYXRpb24iOnsidGl0bGUiOiJBdXRoZW50aWNhdGlvbiIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImNyZWRlbnRpYWxUeXBlIjp7InRpdGxlIjoiQ3JlZGVudGlhbCB0eXBlIiwidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJ1c2VybmFtZSIsIm9uZU9mIjpbeyJjb25zdCI6InVzZXJuYW1lIiwidGl0bGUiOiJVc2VybmFtZSBhbmQgcGFzc3dvcmQifSx7ImNvbnN0Ijoic2VjcmV0IiwidGl0bGUiOiJTU08ifV19fSwiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsiY3JlZGVudGlhbFR5cGUiOnsiY29uc3QiOiJ1c2VybmFtZSJ9fX0sInRoZW4iOnsicHJvcGVydGllcyI6eyJ1c2VybmFtZUFuZFBhc3N3b3JkIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InVzZXJuYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlVzZXJuYW1lIn0sInBhc3N3b3JkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBhc3N3b3JkIn19LCJyZXF1aXJlZCI6WyJ1c2VybmFtZSIsInBhc3N3b3JkIl19fSwicmVxdWlyZWQiOlsidXNlcm5hbWVBbmRQYXNzd29yZCJdfX0seyJpZiI6eyJwcm9wZXJ0aWVzIjp7ImNyZWRlbnRpYWxUeXBlIjp7ImNvbnN0Ijoic2VjcmV0In19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7InNzbyI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJTU08ifX0sInJlcXVpcmVkIjpbInNzbyJdfX1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwiZXhwZXJpbWVudGFsX2RlZmF1bHRGb3JtU3RhdGVCZWhhdmlvciI6eyJhcnJheU1pbkl0ZW1zIjp7InBvcHVsYXRlIjoicG9wdWxhdGUiLCJtZXJnZUV4dHJhRGVmYXVsdHMiOmZhbHNlfSwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifSwibm9IdG1sNVZhbGlkYXRlIjp0cnVlfX0=) when you submit an empty username / password (pasted below), you will see that neither of the individual username nor password fields are marked as having an error. So RJSF has no idea that the errors should be applied to these fields in particular.

Some other options are to write custom logic and [transform the errors](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#transformerrors) to specifically mark the IDs of the fields where there are errors, or to restructure your schema to use `oneOf` instead of `if`/`then`.


Raw Ajv errors:

```json
{
  "errors": [
    {
      "instancePath": "/authentication",
      "schemaPath": "#/properties/authentication/allOf/0/then/required",
      "keyword": "required",
      "params": {
        "missingProperty": "usernameAndPassword"
      },
      "message": "must have required property 'usernameAndPassword'",
      "schema": [
        "usernameAndPassword"
      ],
      "parentSchema": {
        "properties": {
          "usernameAndPassword": {
            "type": "object",
            "properties": {
              "username": {
                "type": "string",
                "title": "Username"
              },
              "password": {
                "type": "string",
                "title": "Password"
              }
            },
            "required": [
              "username",
              "password"
            ]
          }
        },
        "required": [
          "usernameAndPassword"
        ]
      },
      "data": {
        "credentialType": "username"
      }
    },
    {
      "instancePath": "/authentication",
      "schemaPath": "#/properties/authentication/allOf/0/if",
      "keyword": "if",
      "params": {
        "failingKeyword": "then"
      },
      "message": "must match \"then\" schema",
      "schema": {
        "properties": {
          "credentialType": {
            "const": "username"
          }
        }
      },
      "parentSchema": {
        "if": {
          "properties": {
            "credentialType": {
              "const": "username"
            }
          }
        },
        "then": {
          "properties": {
            "usernameAndPassword": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string",
                  "title": "Username"
                },
                "password": {
                  "type": "string",
                  "title": "Password"
                }
              },
              "required": [
                "username",
                "password"
              ]
            }
          },
          "required": [
            "usernameAndPassword"
          ]
        }
      },
      "data": {
        "credentialType": "username"
      }
    }
  ]
}
```

**Comment by alfonsoar** [comment]
Thanks nick for the response, I agree and don't think the issue is with RJSF itself. I also appreciate the additional suggestions you provided, below you will find some of my thoughts for each one. Let me know what you think. 

> write custom logic and [transform the errors](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#transformerrors) to specifically mark the IDs of the fields where there are errors

Did not know about this. Do you know why we don't pass `schema` to this function and we only pass `uiSchema` and `errors` ? If we passed the `schema` I could write a quick look up function that checks if the property for a given error has "children". For example, in this case if I see an error with the name `required` I could look up the property in the schema and If I see it has childrenm then generate two errors for those children. 

<img width="423" alt="Screenshot 2024-08-18 at 1 39 54 PM" src="https://github.com/user-attachments/assets/064796c0-0b1d-4ada-bcc4-82fd5ebb1609">


> to restructure your schema to use oneOf instead of if/then

Are you able to expand further how I could accomplish this? I already use `oneOf` in my schema but not following how I could accomplish what I need. 


> even add custom logic to these fields

I'm trying to find a "generic" solution and rather not tie my logic to these specific username/password fields. I am working on a library that is used for different use cases so having it tied to these to fields would be a PITA. 

Finally, do you have any insight if we could pass the full `errorSchema` to the `BaseInputTemplate` ? ( I could help contribute this if it's a good idea)

**Comment by alfonsoar** [comment]
Hi @abdalla-rko - thanks for the reply, I tried the new schema you provided in this playground but it does not appear to be working? What I'm I missing? https://stackblitz.com/edit/vitejs-vite-1ntklb?file=src%2FApp.tsx

> If you want to pass the full errorSchema to the BaseInputTemplate you need to build a custom ObjectField and ArrayField that passes the full errorSchema to its properties/items.

Do you have any examples or pointers on how to do this? My understanding is you would need to use something like `React. cloneElement` in order to force new props onto the specific content element. 

https://github.com/rjsf-team/react-jsonschema-form/blob/a7b25e8a1803149eccc4fd175ab6412d17cdf77c/packages/utils/src/types.ts#L638

**Comment by abdalla-rko** [comment]
Sorry, I gave you a schema without testing it on your playground, but it works on the rjsf playground. It seems to work on the rjsf playground because the formData **editor** is initially an empty object and it changes when the computedDefaults are set with the following value : 
```json 
{
  "authentication": {
    "credentialType": "username"
  }
}
```
The formData **editor** will update the **formData** state which passed to the rjsf Fom and this triggers a **componentDidUpdate** in the form, which will try to get **computedDefaults** again. However now the difference is that it has the previous set **computedDefault** as **formData** (the json object above) and because of this the **dependencies** get resolved and **formData** will be set to: 
```json 
{
  "authentication": {
    "credentialType": "username",
    "usernameAndPassword": {}
  }
}
```

So this is a bug in our **computedDefault** method in the getDefaultFormState file in Utils. I'll work on it and create a pr. For now you can do a workaround where you make **formData** observable and update the **formData** state after the componentDidMount which results in the same behavior as in the rjsf playground.

As for how to pass the full **errorSchema** to the BaseInputTemplate, sorry I have not tried this and I don't have any examples or pointers.

**Comment by alfonsoar** [comment]
Hi @abdalla-rko - Thanks for getting #4282 over the line, unfortunately it seems we have not fully fixed the issues with dependancies yet. I tested the new version (`5.21.1`) which includes your fix here: https://stackblitz.com/edit/vitejs-vite-ojdqpm?file=src%2FApp.tsx

You will notice that if you hit submit before interacting with the form the username and password will not be marked as error state. Looking at the `formData` I still see that `userNameAndPassword` are missing. 

Let me know if you have any thoughts on this, i do plan to dig deeper into the issue but wanted to hear your thoughts since you are more familiar.

**Comment by abdalla-rko** [comment]
Hi @alfonsoar, you're still using **@rjsf/utils v5.20.0**(check package-lock.json). This is because you're not installing the latest **@rjsf/utils** and **@rjsf/core** has **@rjsf/utils v^5.20.x** as a peer dependency. I have tested it with **@rjsf/utils v5.21.1** in your example and it works as expected. So just include **@rjsf/utils** it in your package.json.

**Comment by alfonsoar** [comment]
Hi @abdalla-rko - Thanks for highlighting that! it's all working as expected. Thanks again for all the help here
