### ISSUE TITLE
onBlur example

### ISSUE THREAD

**Issue by alexandroscgb** [rjsf-team/react-jsonschema-form#618]
Hi.

I'm to react so I don't know how to annotate a field with the onBlur event and define inside the playground.
The playground have a different syntax to the examples in the documentation page.
Could someone give me an example of an onBlur event on a field?

Thank you.

**Comment by ml242** [comment]
I'm also curious about this. It doesn't seem like you have access to formData the same way you do with onChange, which I would prefer not to use because it's pretty intrusive on long fields and onSubmit, which is too far from the user behaviour. There was a pull request accepted to implement this in .42 but the documentation wasn't updated.

**Comment by nikhil-ks** [comment]
I've been looking for an example as well, couldn't find anything, all my problems would be solved if async validation was supported.
