### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by vic4hub** [rjsf-team/react-jsonschema-form#696]
Apologies for posting it here, are there any plans to have this work with react-native?

**Comment by glasserc** [comment]
It isn't really a priority for our team, but we don't have any reason not to support it. Is something missing that is necessary for it to work? I would be happy to look at a PR.

**Comment by bherila** [comment]
I think all the widgets would need to be rewritten for react native, no?

**Comment by glasserc** [comment]
I see. I hadn't looked at react-native before. That seems quite invasive. Is our current "widget overriding" support sufficient that someone could write support for this as a third-party library?

**Comment by Dreyer** [comment]
I'm also interested in understanding more of what might be involved in supporting React Native. How feasible would it be to modify or extend existing functionality? Or, is this library tied primarily to [kinto-admin](https://github.com/mozilla-services/react-jsonschema-form#philosophy) and therefore this wouldn't make sense or be worthwhile?

Would it be possible to define some of the challenges or work that might be required then those of us with an interest in React Native would be able to contribute in a more meaningful way?

**Comment by savushkin-yauheni** [comment]
Hi. Do you have a rough estimate of this enhancement ?

**Comment by epicfaace** [comment]
@savushkin-yauheni it would probably require overriding all the widgets and templates to use React Native components instead of HTML tag components. It would probably be best to put this in a separate library that extends rjsf. It might be a substantial amount of work to do so -- but you're welcome to get started with it if you're willing and we can help you along!

**Comment by CatchSandeepVaid** [comment]
Any updates on this? I think this is an important feature...

**Comment by epicfaace** [comment]
Yes, this would be a great feature. It would probably be implemented using `withTheme` as we now have it, with all the widgets/fields/components overridden by React Native-compatible components. If someone wants to take this up, that would be awesome.

**Comment by zhigang1992** [comment]
I've started to work on this today,

![Screen Shot 2019-12-29 at 7 30 44 PM](https://user-images.githubusercontent.com/1057756/71556318-0bc01f00-2a72-11ea-8bb6-4009765b8758.png)
![Screen Shot 2019-12-29 at 7 31 19 PM](https://user-images.githubusercontent.com/1057756/71556319-0bc01f00-2a72-11ea-8324-c9422b7f66a4.png)


https://github.com/zhigang1992/react-native-jsonschema-form

Should be able to publish in the next week or two.

**Comment by zhigang1992** [comment]
It's published now https://github.com/zhigang1992/react-native-jsonschema-form

Since the `form` is still using HTML form. there are some hacks required. (e.g. `tagName`)

https://github.com/zhigang1992/react-native-jsonschema-form/blob/master/rjsf-native/src/index.tsx#L8

Also `MultiSchemaField` has hardcoded `div` and styles, somehow the material-ui theme also doesn't override.

This will be required for `anyOf`.

Which hopefully we can later make them customizable through the theme.

**Comment by epicfaace** [comment]
@zhigang1992 cool, are you interested in making this into a PR?

**Comment by cpojer** [comment]
There was no current solution that worked or was up-to-date. Now there is, and it's tracking rjsf v6: https://github.com/nkzw-tech/react-native-jsonschema-form
