### ISSUE TITLE
Using boolean field in dependency block

### ISSUE THREAD

**Issue by Armondel** [rjsf-team/react-jsonschema-form#867]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Hello there, I just faced the following problem: if I create a dependency that has base of Boolean field, then, if this field is False, it cannot pass the dependency validation process due to passing a False value to "if" check.

### Steps to Reproduce

1. Create scheme with two fields: first - boolean, second - string.
2. Create dependency block that using a boolean value to change the string value.
3. Open debugger and go to utils.js, to 551 row, a function called withExactlyOneSubschema.
4. You can see the problem when "conditionPropertySchema" is being passed to following if loop.

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/f2y3fq7L/152/)

#### Expected behavior

Pass condition check, change data accordingly.

#### Actual behavior

Condition check is ignored and data doesn't change at all.

### Version

1.0.1

**Comment by epicfaace** [comment]
@Armondel the jsfiddle you've sent is no longer working, it looks like this one shows the proper problem:

https://jsfiddle.net/epicfaace/7mzv1pLk/

@glasserc did we somehow have an old schema type that stopped working after an update or something?

**Comment by glasserc** [comment]
I don't think the first fiddle should have ever worked but maybe I'm missing something.

The second fiddle behaves more-or-less the way I would expect it to: when you check `isEnabled`, it shows `enabled` in the select box for `description`. When you uncheck `isEnabled`, it shows `disabled` in the select box for `description`. If `enabled` was previously selected, it changes to a blank field. The only thing that may not be ideal is that it uses a select box rather than just filling in the data, but I think that's because the string field doesn't expect to get set to a single constant value.

**Comment by glasserc** [comment]
At first, the form data is `{}`, so `isEnabled` isn't present at all, so it doesn't trigger any dependencies. If you add `default: false` to the `isEnabled` schema, then "disabled" shows up on load: https://jsfiddle.net/e64scboh/

I guess conceptually this isn't great because the checkbox UI doesn't let you distinguish between `false` and "missing", but I don't really have any good ideas on how to address it.
