### ISSUE TITLE
null formData enum field validation error on submit

### ISSUE THREAD

**Issue by nikordaris** [rjsf-team/react-jsonschema-form#870]
### Description

When using an enum type with select widget if the formData sets the enum field to null a subsequent form submit will trigger a validation error saying the value is not one of the allowed values. Setting the field to undefined does not trigger this bug. This is particularly annoying when using url query params to initialize the the fields such that you want to explicitly override a default value to be empty.

### Steps to Reproduce

1. jsonschema with enum property
2. set formData for enum property to null
3. submit the form

#### Expected behavior

I expect the validation to be the same as an undefined value

#### Actual behavior

Validation error stating the enum field is not one of the allowed values

### Version

1.0.2

**Comment by OliverLeighC** [comment]
Did this ever get solved? I'm still running into this on version 3.2.1

**Comment by jacqueswho** [comment]
@OliverLeighC is this correct? has been fixed in the latest version

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0ZXN0IjpudWxsfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7InRlc3QiOnsidHlwZSI6ImJvb2xlYW4iLCJlbnVtIjpbdHJ1ZSxmYWxzZV19fSwicmVxdWlyZWQiOlsidGVzdCJdfSwidWlTY2hlbWEiOnsidWk6dGl0bGUiOiJPdmVyd3JpdGUgQm9vbGVhbiBUaXRsZSIsInVpOmRlc2NyaXB0aW9uIjoiT3ZlcndpdGUgQm9vbGVhbiBEZXNjcmlwdGlvbiJ9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlIjpmYWxzZSwicmVhZG9ubHkiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=

**Comment by heath-freenome** [comment]
Closing issue as it appears to have been fixed
