### ISSUE TITLE
"title" in jsonschema vs "ui:title" in uischema

### ISSUE THREAD

**Issue by Eric24** [rjsf-team/react-jsonschema-form#957]
Which of these props is preferred? "ui:title" seems like the best option, since the field title/label is purely cosmetic (i.e. it does not affect the schema). But "ui:title" doesn't seem to work across the board. For example, it has no effect for array or boolean types ("title" in the jsonschema works fine for both).

There are also examples that have both "title" and "ui:title" defined. Is there any reason for this or are these examples "in transition"?

**Comment by epicfaace** [comment]
It's also strange because

title is preferred over ui:title for [ObjectFieldTemplate](https://github.com/mozilla-services/react-jsonschema-form/blob/f9d4c63cac24146e522528d33eb04f465464e052/src/components/fields/ObjectField.js)

ui:title is preferred over title for [ArrayField](https://github.com/mozilla-services/react-jsonschema-form/blob/2d63594e075bba3b134ef09709c773a9ea037923/src/components/fields/ArrayField.js) and [SchemaField](https://github.com/mozilla-services/react-jsonschema-form/blob/98952b7f2a6add8909a2c7209797f3770d4a04f7/src/components/fields/SchemaField.js)

We need to harmonize this behavior to at least make it consistent.

**Comment by Eric24** [comment]
Just a few thoughts on this:
- While "title" is defined as a valid JSON Schema keyword (https://json-schema.org/understanding-json-schema/reference/generic.html), my interpretation is that it's meant to describe the schema, combined with "description", not necessarily something that should be displayed in a UI.
- In order to separate the data from the presentation layer, "ui:title" seems like a more appropriate way to express the title of a field in a UI.
- For i18n, the "title" in the schema may be in one language (native to the developer, for example), while there may be multiple UI schemas with different "ui:title" languages, based on the UI user's preference.
- For backward compatibility, perhaps "ui:title" should be the standard, with fallback to "title" if "ui:title" isn't defined.

PS - I would also suggest that the same could be said for "ui:description" with fallback to "description".

**Comment by C-odes** [comment]
PLEASE YES. It's  weird,  title has no effect sometimes and its not even showing even with the title in jsonschema. Only label is shown. Gona open an issue on this.

**Comment by heath-freenome** [comment]
In v5 `ui:title` and `ui:description` over `title` and `description` were standardized. Closing
